In [2]:
pip install "lxml[html_clean]"

Requirement already satisfied: lxml[html_clean] in c:\users\aman0\miniconda3\lib\site-packages (5.3.0)
Collecting lxml-html-clean (from lxml[html_clean])
  Downloading lxml_html_clean-0.4.2-py3-none-any.whl.metadata (2.4 kB)
Downloading lxml_html_clean-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: lxml-html-clean
Successfully installed lxml-html-clean-0.4.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import os
import sys
# Get the current directory.
current_dir = os.getcwd()
# Add the `src` folder to the PYTHONPATH.
sys.path.append(os.path.join(current_dir, "../src"))
from scraping_functions import *

In [9]:
tournaments = pd.DataFrame({'Name' : [], 'Id' : [], 'Start Date' : [], 'End Date' : []})
for year in range(2024, 2000, -1):
    addition = collect_tournaments(year)
    tournaments = pd.concat([tournaments, addition], axis = 0)

Acapulco 807 2024
Adelaide 8998 2024
Almaty 9410 2024
Antwerp 7485 2024
Atlanta 6116 2024
Auckland 301 2024
Australian-Open 580 2024
Barcelona 425 2024
Basel 328 2024
Bastad 316 2024
Beijing 747 2024
Belgrade 4787 2024
Brisbane 339 2024
Bucharest 4462 2024
Buenos-Aires 506 2024
Chengdu 7581 2024
Cincinnati 422 2024
Cordoba 9158 2024
Dallas 424 2024
Davis-Cup-Finals 8099 2024
Davis-Cup-Finals-Group-Stage 8097 2024
Davis-Cup-Qualifiers 8096 2024
Delray-Beach 499 2024
Doha 451 2024
Dubai 495 2024
Eastbourne 741 2024
Estoril 7290 2024
Geneva 322 2024
Gstaad 314 2024
Halle 500 2024
Hamburg 414 2024
Hangzhou 4713 2024
Hong-Kong 336 2024
Houston 717 2024
Indian-Wells 404 2024
Kitzbuhel 319 2024
Laver-Cup 9210 2024
London 311 2024
Los-Cabos 7480 2024
Lyon 7694 2024
Madrid 1536 2024
Mallorca 8994 2024
Marrakech 360 2024
Marseille 496 2024
Metz 341 2024
Miami 403 2024
Monte-Carlo 410 2024
Montpellier 375 2024
Montreal 421 2024
Munich 308 2024
Newport 315 2024
Next-Gen-Atp-Finals 7696 2024
Nitto-Atp-Finals 605 2024
Paris 352 2024
Paris-Olympics 96 2024
Rio-De-Janeiro 6932 2024
Roland-Garros 520 2024
Rome 416 2024
Rotterdam 407 2024
Santiago 8996 2024
Shanghai 5014 2024
'S-Hertogenbosch 440 2024
Stockholm 429 2024
Stuttgart 321 2024
Tokyo 329 2024
Umag 439 2024
United-Cup 9900 2024
Us-Open 560 2024
Vienna 337 2024
Washington 418 2024
Wimbledon 540 2024
Winston-Salem 6242 2024

C:\Users\aman0\AppData\Local\Temp\ipykernel_14916\3582805999.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tournaments = pd.concat([tournaments, addition], axis = 0)

Acapulco 807 2023
Adelaide-1 2843 2023
Adelaide-2 8998 2023
Antwerp 7485 2023
Astana 9410 2023
Atlanta 6116 2023
Auckland 301 2023
Australian-Open 580 2023
Banja-Luka 2841 2023
Barcelona 425 2023
Basel 328 2023
Bastad 316 2023
Beijing 747 2023
Buenos-Aires 506 2023
Chengdu 7581 2023
Cincinnati 422 2023
Cordoba 9158 2023
Dallas 424 2023
Davis-Cup-Finals 8099 2023
Davis-Cup-Finals-Group-Stage 8097 2023
Davis-Cup-Qualifiers 8096 2023
Delray-Beach 499 2023
Doha 451 2023
Dubai 495 2023
Eastbourne 741 2023
Estoril 7290 2023
Geneva 322 2023
Gstaad 314 2023
Halle 500 2023
Hamburg 414 2023
Houston 717 2023
Indian-Wells 404 2023
Kitzbuhel 319 2023
Laver-Cup 9210 2023
London 311 2023
Los-Cabos 7480 2023
Lyon 7694 2023
Madrid 1536 2023
Mallorca 8994 2023
Marrakech 360 2023
Marseille 496 2023
Metz 341 2023
Miami 403 2023
Monte-Carlo 410 2023
Montpellier 375 2023
Munich 308 2023
Newport 315 2023
Next-Gen-Atp-Finals 7696 2023
Nitto-Atp-Finals 605 2023
Paris 352 2023
Pune 891 2023
Rio-De-Janeiro 6932 2023
Roland-Garros 520 2023
Rome 416 2023
Rotterdam 407 2023
Santiago 8996 2023
Shanghai 5014 2023
'S-Hertogenbosch 440 2023
Sofia 7434 2023
Stockholm 429 2023
Stuttgart 321 2023
Tokyo 329 2023
Toronto 421 2023
Umag 439 2023
United-Cup 9900 2023
Us-Open 560 2023
Vienna 337 2023
Washington 418 2023
Wimbledon 540 2023
Winston-Salem 6242 2023
Zhuhai 9164 2023
Acapulco 807 2022
Adelaide-1 8998 2022
Adelaide-2 9667 2022
Antwerp 7485 2022
Astana 9410 2022
Atlanta 6116 2022
Atp-Cup 8888 2022
Australian-Open 580 2022
Barcelona 425 2022
Basel 328 2022
Bastad 316 2022
Belgrade 5053 2022
Buenos-Aires 506 2022
Cincinnati 422 2022
Cordoba 9158 2022
Dallas 424 2022
Davis-Cup-Finals 8099 2022
Davis-Cup-Finals-Group-Stage 8097 2022
Davis-Cup-Qualifiers-And-Groups-I-&Amp;-Ii-Playoffs 8096 2022
Davis-Cup-World-Group-I 8095 2022
Davis-Cup-World-Group-Ii 8098 2022
Delray-Beach 499 2022
Doha 451 2022
Dubai 495 2022
Eastbourne 741 2022
Estoril 7290 2022
Florence 2805 2022
Geneva 322 2022
Gijon 2807 2022
Gstaad 314 2022
Halle 500 2022
Hamburg 414 2022
Houston 717 2022
Indian-Wells 404 2022
Intesa-Sanpaolo-Next-Gen-Atp-Finals 7696 2022
Kitzbuhel 319 2022
Laver-Cup 9210 2022
London 311 2022
Los-Cabos 7480 2022
Lyon 7694 2022
Madrid 1536 2022
Mallorca 8994 2022
Marrakech 360 2022
Marseille 496 2022
Melbourne 9665 2022
Metz 341 2022
Miami 403 2022
Monte-Carlo 410 2022
Montpellier 375 2022
Montreal 421 2022
Munich 308 2022
Naples 2809 2022
Newport 315 2022
Nitto-Atp-Finals 605 2022
Paris 352 2022
Pune 891 2022
Rio-De-Janeiro 6932 2022
Roland-Garros 520 2022
Rome 416 2022
Rotterdam 407 2022
San-Diego 9569 2022
Santiago 8996 2022
Seoul 4140 2022
'S-Hertogenbosch 440 2022
Sofia 7434 2022
Stockholm 429 2022
Stuttgart 321 2022
Sydney 9663 2022
Tel-Aviv 4138 2022
Tokyo 329 2022
Umag 439 2022
Us-Open 560 2022
Vienna 337 2022
Washington 418 2022
Wimbledon 540 2022
Winston-Salem 6242 2022
Acapulco 807 2021
Antalya 9426 2021
Antwerp 7485 2021
Atlanta 6116 2021
Atp-Cup 8888 2021
Auckland 301 2021
Australian-Open 580 2021
Barcelona 425 2021
Basel 328 2021
Bastad 316 2021
Beijing 747 2021
Belgrade-1 5053 2021
Belgrade-2 9512 2021
Buenos-Aires 506 2021
Cagliari 9481 2021
Chengdu 7581 2021
Cincinnati 422 2021
Cordoba 9158 2021
Delray-Beach 499 2021
Doha 451 2021
Dubai 495 2021
Eastbourne 741 2021
Estoril 7290 2021
Geneva 322 2021
Gstaad 314 2021
Halle 500 2021
Hamburg 414 2021
Houston 717 2021
Indian-Wells 404 2021
Intesa-Sanpaolo-Next-Gen-Atp-Finals 7696 2021
Kitzbuhel 319 2021
Laver-Cup 9210 2021
London 311 2021
Los-Cabos 7480 2021
Lyon 7694 2021
Madrid 1536 2021
Mallorca 8994 2021
Marbella 9462 2021
Marrakech 360 2021
Marseille 496 2021
Melbourne-1 8998 2021
Melbourne-2 9428 2021
Metz 341 2021
Miami 403 2021
Monte-Carlo 410 2021
Montpellier 375 2021
Moscow 438 2021
Munich 308 2021
New-York 424 2021
Newport 315 2021
Nitto-Atp-Finals 605 2021
Nur-Sultan 9410 2021
Paris 352 2021
Parma 9510 2021
Pune 891 2021
Rio-De-Janeiro 6932 2021
Roland-Garros 520 2021
Rome 416 2021
Rotterdam 407 2021
San-Diego 9569 2021
Santiago 8996 2021
Shanghai 5014 2021
'S-Hertogenbosch 440 2021
Singapore 9460 2021
Sofia 7434 2021
St.-Petersburg 568 2021
Stockholm 429 2021
Stuttgart 321 2021
Tokyo 329 2021
Tokyo-Olympics 96 2021
Toronto 421 2021
Umag 439 2021
Us-Open 560 2021
Vienna 337 2021
Washington 418 2021
Wimbledon 540 2021
Winston-Salem 6242 2021
Zhuhai 9164 2021
Acapulco 807 2020
Adelaide 8998 2020
Antwerp 7485 2020
Atlanta 6116 2020
Atp-Cup 8888 2020
Auckland 301 2020
Australian-Open 580 2020
Barcelona 425 2020
Basel 328 2020
Bastad 316 2020
Beijing 747 2020
Budapest 7648 2020
Buenos-Aires 506 2020
Chengdu 7581 2020
Cologne-1 9404 2020
Cologne-2 9406 2020
Cordoba 9158 2020
Davis-Cup-Finals 8099 2020
Davis-Cup-Group-Ii 8097 2020
Davis-Cup-Groups-I-And-Ii 8098 2020
Davis-Cup-Qualifiers 8096 2020
Delray-Beach 499 2020
Doha 451 2020
Dubai 495 2020
Eastbourne 741 2020
Estoril 7290 2020
Geneva 322 2020
Gstaad 314 2020
Halle 500 2020
Hamburg 414 2020
Houston 717 2020
Indian-Wells 404 2020
Kitzbuhel 319 2020
Laver-Cup 9210 2020
London 311 2020
Los-Cabos 7480 2020
Lyon 7694 2020
Madrid 1536 2020
Mallorca 8994 2020
Marrakech 360 2020
Marseille 496 2020
Metz 341 2020
Miami 403 2020
Monte-Carlo 410 2020
Montpellier 375 2020
Moscow 438 2020
Munich 308 2020
New-York 422 2020
New-York 424 2020
Newport 315 2020
Next-Gen-Atp-Finals 7696 2020
Nitto-Atp-Finals 605 2020
Nur-Sultan 9410 2020
Paris 352 2020
Pune 891 2020
Rio-De-Janeiro 6932 2020
Roland-Garros 520 2020
Rome 416 2020
Rotterdam 407 2020
Santiago 8996 2020
Sardinia 9408 2020
Shanghai 5014 2020
'S-Hertogenbosch 440 2020
Sofia 7434 2020
St.-Petersburg 568 2020
Stockholm 429 2020
Stuttgart 321 2020
Tokyo 329 2020
Tokyo-Olympics 96 2020
Toronto 421 2020
Umag 439 2020
Us-Open 560 2020
Vienna 337 2020
Washington 418 2020
Wimbledon 540 2020
Winston-Salem 6242 2020
Zhuhai 9164 2020
Acapulco 807 2019
Antalya 7650 2019
Antwerp 7485 2019
Atlanta 6116 2019
Auckland 301 2019
Australian-Open 580 2019
Barcelona 425 2019
Basel 328 2019
Bastad 316 2019
Beijing 747 2019
Brisbane 339 2019
Budapest 7648 2019
Buenos-Aires 506 2019
Chengdu 7581 2019
Cincinnati 422 2019
Cordoba 9158 2019
Davis-Cup 8099 2019
Davis-Cup-Group-Ii 8097 2019
Davis-Cup-Groups-I-And-Ii 8098 2019
Davis-Cup-Qualifiers 8096 2019
Delray-Beach 499 2019
Doha 451 2019
Dubai 495 2019
Eastbourne 741 2019
Estoril 7290 2019
Geneva 322 2019
Gstaad 314 2019
Halle 500 2019
Hamburg 414 2019
Houston 717 2019
Indian-Wells 404 2019
Kitzbuhel 319 2019
Laver-Cup 9210 2019
London 311 2019
Los-Cabos 7480 2019
Lyon 7694 2019
Madrid 1536 2019
Marrakech 360 2019
Marseille 496 2019
Metz 341 2019
Miami 403 2019
Monte-Carlo 410 2019
Montpellier 375 2019
Montreal 421 2019
Moscow 438 2019
Munich 308 2019
New-York 424 2019
Newport 315 2019
Next-Gen-Atp-Finals 7696 2019
Nitto-Atp-Finals 605 2019
Paris 352 2019
Pune 891 2019
Rio-De-Janeiro 6932 2019
Roland-Garros 520 2019
Rome 416 2019
Rotterdam 407 2019
Sao-Paulo 533 2019
Shanghai 5014 2019
'S-Hertogenbosch 440 2019
Sofia 7434 2019
St.-Petersburg 568 2019
Stockholm 429 2019
Stuttgart 321 2019
Sydney 338 2019
Tokyo 329 2019
Umag 439 2019
Us-Open 560 2019
Vienna 337 2019
Washington 418 2019
Wimbledon 540 2019
Winston-Salem 6242 2019
Zhuhai 9164 2019
Acapulco 807 2018
Antalya 7650 2018
Antwerp 7485 2018
Atlanta 6116 2018
Auckland 301 2018
Australian-Open 580 2018
Barcelona 425 2018
Basel 328 2018
Bastad 316 2018
Beijing 747 2018
Brisbane 339 2018
Budapest 7648 2018
Buenos-Aires 506 2018
Chengdu 7581 2018
Cincinnati 422 2018
Davis-Cup 8099 2018
Davis-Cup-First-Round 8096 2018
Davis-Cup-Quarter-Finals 8097 2018
Davis-Cup-Semi-Finals 8098 2018
Delray-Beach 499 2018
Doha 451 2018
Dubai 495 2018
Eastbourne 741 2018
Estoril 7290 2018
Geneva 322 2018
Gstaad 314 2018
Halle 500 2018
Hamburg 414 2018
Houston 717 2018
Indian-Wells 404 2018
Istanbul 7163 2018
Kitzbuhel 319 2018
Laver-Cup 9210 2018
London 311 2018
Los-Cabos 7480 2018
Lyon 7694 2018
Madrid 1536 2018
Marrakech 360 2018
Marseille 496 2018
Metz 341 2018
Miami 403 2018
Monte-Carlo 410 2018
Montpellier 375 2018
Moscow 438 2018
Munich 308 2018
New-York 424 2018
Newport 315 2018
Next-Gen-Atp-Finals 7696 2018
Nitto-Atp-Finals 605 2018
Paris 352 2018
Pune 891 2018
Quito 7161 2018
Rio-De-Janeiro 6932 2018
Roland-Garros 520 2018
Rome 416 2018
Rotterdam 407 2018
Sao-Paulo 533 2018
Shanghai 5014 2018
Shenzhen 6967 2018
'S-Hertogenbosch 440 2018
Sofia 7434 2018
St.-Petersburg 568 2018
Stockholm 429 2018
Stuttgart 321 2018
Sydney 338 2018
Tokyo 329 2018
Toronto 421 2018
Umag 439 2018
Us-Open 560 2018
Vienna 337 2018
Washington 418 2018
Wimbledon 540 2018
Winston-Salem 6242 2018
Acapulco 807 2017
Antalya 7650 2017
Antwerp 7485 2017
Atlanta 6116 2017
Auckland 301 2017
Australian-Open 580 2017
Barcelona 425 2017
Basel 328 2017
Bastad 316 2017
Beijing 747 2017
Brisbane 339 2017
Budapest 7648 2017
Buenos-Aires 506 2017
Chengdu 7581 2017
Chennai 891 2017
Cincinnati 422 2017
Davis-Cup 8099 2017
Davis-Cup-First-Round 8096 2017
Davis-Cup-Quarter-Finals 8097 2017
Davis-Cup-Semi-Finals 8098 2017
Delray-Beach 499 2017
Doha 451 2017
Dubai 495 2017
Eastbourne 741 2017
Estoril 7290 2017
Geneva 322 2017
Gstaad 314 2017
Halle 500 2017
Hamburg 414 2017
Houston 717 2017
Indian-Wells 404 2017
Istanbul 7163 2017
Kitzbuhel 319 2017
Laver-Cup 9210 2017
London 311 2017
Los-Cabos 7480 2017
Lyon 7694 2017
Madrid 1536 2017
Marrakech 360 2017
Marseille 496 2017
Memphis 424 2017
Metz 341 2017
Miami 403 2017
Monte-Carlo 410 2017
Montpellier 375 2017
Montreal 421 2017
Moscow 438 2017
Munich 308 2017
Newport 315 2017
Next-Gen-Atp-Finals 7696 2017
Nitto-Atp-Finals 605 2017
Paris 352 2017
Quito 7161 2017
Rio-De-Janeiro 6932 2017
Roland-Garros 520 2017
Rome 416 2017
Rotterdam 407 2017
Sao-Paulo 533 2017
Shanghai 5014 2017
Shenzhen 6967 2017
'S-Hertogenbosch 440 2017
Sofia 7434 2017
St.-Petersburg 568 2017
Stockholm 429 2017
Stuttgart 321 2017
Sydney 338 2017
Tokyo 329 2017
Umag 439 2017
Us-Open 560 2017
Vienna 337 2017
Washington 418 2017
Wimbledon 540 2017
Winston-Salem 6242 2017
Acapulco 807 2016
Antwerp 7485 2016
Atlanta 6116 2016
Atp-Finals 605 2016
Auckland 301 2016
Australian-Open 580 2016
Barcelona 425 2016
Basel 328 2016
Bastad 316 2016
Beijing 747 2016
Brisbane 339 2016
Bucharest 773 2016
Buenos-Aires 506 2016
Chengdu 7581 2016
Chennai 891 2016
Cincinnati 422 2016
Davis-Cup 8099 2016
Davis-Cup-First-Round 8096 2016
Davis-Cup-Quarter-Finals 8097 2016
Davis-Cup-Semi-Finals 8098 2016
Delray-Beach 499 2016
Doha 451 2016
Dubai 495 2016
Estoril 7290 2016
Geneva 322 2016
Gstaad 314 2016
Halle 500 2016
Hamburg 414 2016
Houston 717 2016
Indian-Wells 404 2016
Istanbul 7163 2016
Kitzbuhel 319 2016
London 311 2016
Los-Cabos 7480 2016
Madrid 1536 2016
Marrakech 360 2016
Marseille 496 2016
Memphis 424 2016
Metz 341 2016
Miami 403 2016
Monte-Carlo 410 2016
Montpellier 375 2016
Moscow 438 2016
Munich 308 2016
Newport 315 2016
Nice 6120 2016
Nottingham 741 2016
Paris 352 2016
Quito 7161 2016
Rio-De-Janeiro 6932 2016
Rio-Olympics 96 2016
Roland-Garros 520 2016
Rome 416 2016
Rotterdam 407 2016
Sao-Paulo 533 2016
Shanghai 5014 2016
Shenzhen 6967 2016
'S-Hertogenbosch 440 2016
Sofia 7434 2016
St.-Petersburg 568 2016
Stockholm 429 2016
Stuttgart 321 2016
Sydney 338 2016
Tokyo 329 2016
Toronto 421 2016
Umag 439 2016
Us-Open 560 2016
Vienna 337 2016
Washington 418 2016
Wimbledon 540 2016
Winston-Salem 6242 2016
Acapulco 807 2015
Atlanta 6116 2015
Atp-Finals 605 2015
Auckland 301 2015
Australian-Open 580 2015
Barcelona 425 2015
Basel 328 2015
Bastad 316 2015
Beijing 747 2015
Bogota 6718 2015
Brisbane 339 2015
Bucharest 773 2015
Buenos-Aires 506 2015
Casablanca 360 2015
Chennai 891 2015
Cincinnati 422 2015
Davis-Cup 8099 2015
Davis-Cup-First-Round 8096 2015
Davis-Cup-Quarter-Finals 8097 2015
Davis-Cup-Semi-Finals 8098 2015
Delray-Beach 499 2015
Doha 451 2015
Dubai 495 2015
Estoril 7290 2015
Geneva 322 2015
Gstaad 314 2015
Halle 500 2015
Hamburg 414 2015
Houston 717 2015
Indian-Wells 404 2015
Istanbul 7163 2015
Kitzbuhel 319 2015
Kuala-Lumpur 6003 2015
London 311 2015
Madrid 1536 2015
Marseille 496 2015
Memphis 424 2015
Metz 341 2015
Miami 403 2015
Monte-Carlo 410 2015
Montpellier 375 2015
Montreal 421 2015
Moscow 438 2015
Munich 308 2015
Newport 315 2015
Nice 6120 2015
Nottingham 741 2015
Paris 352 2015
Quito 7161 2015
Rio-De-Janeiro 6932 2015
Roland-Garros 520 2015
Rome 416 2015
Rotterdam 407 2015
Sao-Paulo 533 2015
Shanghai 5014 2015
Shenzhen 6967 2015
'S-Hertogenbosch 440 2015
St.-Petersburg 568 2015
Stockholm 429 2015
Stuttgart 321 2015
Sydney 338 2015
Tokyo 329 2015
Umag 439 2015
Us-Open 560 2015
Valencia 573 2015
Vienna 337 2015
Washington 418 2015
Wimbledon 540 2015
Winston-Salem 6242 2015
Zagreb 2276 2015
Acapulco 807 2014
Atlanta 6116 2014
Atp-Finals 605 2014
Auckland 301 2014
Australian-Open 580 2014
Barcelona 425 2014
Basel 328 2014
Bastad 316 2014
Beijing 747 2014
Bogota 6718 2014
Brisbane 339 2014
Bucharest 773 2014
Buenos-Aires 506 2014
Casablanca 360 2014
Chennai 891 2014
Cincinnati 422 2014
Davis-Cup 8099 2014
Delray-Beach 499 2014
Doha 451 2014
Dubai 495 2014
Dusseldorf 6710 2014
Eastbourne 741 2014
Gstaad 314 2014
Halle 500 2014
Hamburg 414 2014
Houston 717 2014
Indian-Wells 404 2014
Kitzbuhel 319 2014
Kuala-Lumpur 6003 2014
London 311 2014
Madrid 1536 2014
Marseille 496 2014
Memphis 424 2014
Metz 341 2014
Miami 403 2014
Monte-Carlo 410 2014
Montpellier 375 2014
Moscow 438 2014
Munich 308 2014
Newport 315 2014
Nice 6120 2014
Oeiras 468 2014
Paris 352 2014
Rio-De-Janeiro 6932 2014
Roland-Garros 520 2014
Rome 416 2014
Rotterdam 407 2014
Sao-Paulo 533 2014
Shanghai 5014 2014
Shenzhen 6967 2014
'S-Hertogenbosch 440 2014
Stockholm 429 2014
Stuttgart 321 2014
Sydney 338 2014
Tokyo 329 2014
Toronto 421 2014
Umag 439 2014
Us-Open 560 2014
Valencia 573 2014
Vienna 337 2014
Vina-Del-Mar 8996 2014
Washington 418 2014
Wimbledon 540 2014
Winston-Salem 6242 2014
Zagreb 2276 2014
Acapulco 807 2013
Atlanta 6116 2013
Atp-Finals 605 2013
Auckland 301 2013
Australian-Open 580 2013
Bangkok 1720 2013
Barcelona 425 2013
Basel 328 2013
Bastad 316 2013
Beijing 747 2013
Bogota 6718 2013
Brisbane 339 2013
Bucharest 773 2013
Buenos-Aires 506 2013
Casablanca 360 2013
Chennai 891 2013
Cincinnati 422 2013
Davis-Cup 8099 2013
Delray-Beach 499 2013
Doha 451 2013
Dubai 495 2013
Dusseldorf 6710 2013
Eastbourne 741 2013
Gstaad 314 2013
Halle 500 2013
Hamburg 414 2013
Houston 717 2013
Indian-Wells 404 2013
Kitzbuhel 319 2013
Kuala-Lumpur 6003 2013
London 311 2013
Madrid 1536 2013
Marseille 496 2013
Memphis 402 2013
Metz 341 2013
Miami 403 2013
Monte-Carlo 410 2013
Montpellier 375 2013
Montreal 421 2013
Moscow 438 2013
Munich 308 2013
Newport 315 2013
Nice 6120 2013
Oeiras 468 2013
Paris 352 2013
Roland-Garros 520 2013
Rome 416 2013
Rotterdam 407 2013
San-Jose 424 2013
Sao-Paulo 533 2013
Shanghai 5014 2013
'S-Hertogenbosch 440 2013
St.-Petersburg 568 2013
Stockholm 429 2013
Stuttgart 321 2013
Sydney 338 2013
Tokyo 329 2013
Umag 439 2013
Us-Open 560 2013
Valencia 573 2013
Vienna 337 2013
Vina-Del-Mar 8996 2013
Washington 418 2013
Wimbledon 540 2013
Winston-Salem 6242 2013
Zagreb 2276 2013
Acapulco 807 2012
Atlanta 6116 2012
Atp-Finals 605 2012
Auckland 301 2012
Australian-Open 580 2012
Bangkok 1720 2012
Barcelona 425 2012
Basel 328 2012
Bastad 316 2012
Beijing 747 2012
Belgrade 5053 2012
Brisbane 339 2012
Bucharest 773 2012
Buenos-Aires 506 2012
Casablanca 360 2012
Chennai 891 2012
Cincinnati 422 2012
Davis-Cup 8099 2012
Delray-Beach 499 2012
Doha 451 2012
Dubai 495 2012
Eastbourne 741 2012
Estoril 468 2012
Gstaad 314 2012
Halle 500 2012
Hamburg 414 2012
Houston 717 2012
Indian-Wells 404 2012
Kitzbuhel 319 2012
Kuala-Lumpur 6003 2012
London 311 2012
London-Olympics 96 2012
Los-Angeles 423 2012
Madrid 1536 2012
Marseille 496 2012
Memphis 402 2012
Metz 341 2012
Miami 403 2012
Monte-Carlo 410 2012
Montpellier 375 2012
Moscow 438 2012
Munich 308 2012
Newport 315 2012
Nice 6120 2012
Paris 352 2012
Roland-Garros 520 2012
Rome 416 2012
Rotterdam 407 2012
San-Jose 424 2012
Sao-Paulo 533 2012
Shanghai 5014 2012
'S-Hertogenbosch 440 2012
St.-Petersburg 568 2012
Stockholm 429 2012
Stuttgart 321 2012
Sydney 338 2012
Tokyo 329 2012
Toronto 421 2012
Umag 439 2012
Us-Open 560 2012
Valencia 573 2012
Vienna 337 2012
Vina-Del-Mar 8996 2012
Washington 418 2012
Wimbledon 540 2012
Winston-Salem 6242 2012
World-Team-Cup 615 2012
Zagreb 2276 2012
Acapulco 807 2011
Atlanta 6116 2011
Atp-Finals 605 2011
Auckland 301 2011
Australian-Open 580 2011
Bangkok 1720 2011
Barcelona 425 2011
Basel 328 2011
Bastad 316 2011
Beijing 747 2011
Belgrade 5053 2011
Brisbane 339 2011
Bucharest 773 2011
Buenos-Aires 506 2011
Casablanca 360 2011
Chennai 891 2011
Cincinnati 422 2011
Costa-Do-Sauipe 533 2011
Davis-Cup 8099 2011
Delray-Beach 499 2011
Doha 451 2011
Dubai 495 2011
Eastbourne 741 2011
Estoril 468 2011
Gstaad 314 2011
Halle 500 2011
Hamburg 414 2011
Houston 717 2011
Indian-Wells 404 2011
Johannesburg 5012 2011
Kitzbuhel 319 2011
Kuala-Lumpur 6003 2011
London 311 2011
Los-Angeles 423 2011
Madrid 1536 2011
Marseille 496 2011
Memphis 402 2011
Metz 341 2011
Miami 403 2011
Monte-Carlo 410 2011
Montreal 421 2011
Moscow 438 2011
Munich 308 2011
Newport 315 2011
Nice 6120 2011
Paris 352 2011
Roland-Garros 520 2011
Rome 416 2011
Rotterdam 407 2011
San-Jose 424 2011
Santiago 8996 2011
Shanghai 5014 2011
'S-Hertogenbosch 440 2011
St.-Petersburg 568 2011
Stockholm 429 2011
Stuttgart 321 2011
Sydney 338 2011
Tokyo 329 2011
Umag 439 2011
Us-Open 560 2011
Valencia 573 2011
Vienna 337 2011
Washington 418 2011
Wimbledon 540 2011
Winston-Salem 6242 2011
World-Team-Cup 615 2011
Zagreb 2276 2011
Acapulco 807 2010
Atlanta 6116 2010
Atp-Finals 605 2010
Auckland 301 2010
Australian-Open 580 2010
Bangkok 1720 2010
Barcelona 425 2010
Basel 328 2010
Bastad 316 2010
Beijing 747 2010
Belgrade 5053 2010
Brisbane 339 2010
Bucharest 773 2010
Buenos-Aires 506 2010
Casablanca 360 2010
Chennai 891 2010
Cincinnati 422 2010
Costa-Do-Sauipe 533 2010
Davis-Cup 8099 2010
Delray-Beach 499 2010
Doha 451 2010
Dubai 495 2010
Eastbourne 741 2010
Estoril 468 2010
Gstaad 314 2010
Halle 500 2010
Hamburg 414 2010
Houston 717 2010
Indian-Wells 404 2010
Johannesburg 5012 2010
Kuala-Lumpur 6003 2010
London 311 2010
Los-Angeles 423 2010
Madrid 1536 2010
Marseille 496 2010
Memphis 402 2010
Metz 341 2010
Miami 403 2010
Monte-Carlo 410 2010
Montpellier 375 2010
Moscow 438 2010
Munich 308 2010
New-Haven 3348 2010
Newport 315 2010
Nice 6120 2010
Paris 352 2010
Roland-Garros 520 2010
Rome 416 2010
Rotterdam 407 2010
San-Jose 424 2010
Santiago 8996 2010
Shanghai 5014 2010
'S-Hertogenbosch 440 2010
St.-Petersburg 568 2010
Stockholm 429 2010
Stuttgart 321 2010
Sydney 338 2010
Tokyo 329 2010
Toronto 421 2010
Umag 439 2010
Us-Open 560 2010
Valencia 573 2010
Vienna 337 2010
Washington 418 2010
Wimbledon 540 2010
World-Team-Cup 615 2010
Zagreb 2276 2010
Acapulco 807 2009
Atp-Finals 605 2009
Auckland 301 2009
Australian-Open 580 2009
Bangkok 1720 2009
Barcelona 425 2009
Basel 328 2009
Bastad 316 2009
Beijing 747 2009
Belgrade 5053 2009
Brisbane 339 2009
Bucharest 773 2009
Buenos-Aires 506 2009
Casablanca 360 2009
Chennai 891 2009
Cincinnati 422 2009
Costa-Do-Sauipe 533 2009
Davis-Cup 8099 2009
Delray-Beach 499 2009
Doha 451 2009
Dubai 495 2009
Eastbourne 741 2009
Estoril 468 2009
Gstaad 314 2009
Halle 500 2009
Hamburg 414 2009
Houston 717 2009
Indian-Wells 404 2009
Indianapolis 419 2009
Johannesburg 5012 2009
Kitzbuhel 319 2009
Kuala-Lumpur 6003 2009
London 311 2009
Los-Angeles 423 2009
Lyon 7309 2009
Madrid 1536 2009
Marseille 496 2009
Memphis 402 2009
Metz 341 2009
Miami 403 2009
Monte-Carlo 410 2009
Montreal 421 2009
Moscow 438 2009
Munich 308 2009
New-Haven 3348 2009
Newport 315 2009
Paris 352 2009
Roland-Garros 520 2009
Rome 416 2009
Rotterdam 407 2009
San-Jose 424 2009
Shanghai 5014 2009
'S-Hertogenbosch 440 2009
St.-Petersburg 568 2009
Stockholm 429 2009
Stuttgart 321 2009
Sydney 338 2009
Tokyo 329 2009
Umag 439 2009
Us-Open 560 2009
Valencia 573 2009
Vienna 337 2009
Vina-Del-Mar 8996 2009

In [35]:
tournaments['Id']=tournaments['Id'].astype('int64')
tournaments['Year'] = tournaments['Start Date'].dt.year
tournaments_df = tournaments.drop_duplicates().set_index(['Name', 'Year'])
tournaments_df = tournaments_df.sort_index()
tournaments_df

                         Id Start Date   End Date
Name             Year
'S-Hertogenbosch 2002   440 2002-06-17 2002-06-23
                 2003   440 2003-06-16 2003-06-22
                 2004   440 2004-06-14 2004-06-20
                 2005   440 2005-06-13 2005-06-19
                 2006   440 2006-06-19 2006-06-25
...                     ...        ...        ...
Zagreb           2015  2276 2015-02-02 2015-02-08
Zhuhai           2019  9164 2019-09-23 2019-09-29
                 2020  9164 2020-09-28 2020-10-04
                 2021  9164 2021-09-27 2021-10-03
                 2023  9164 2023-09-20 2023-09-26

[1624 rows x 3 columns]

In [ ]:
players_df = pd.DataFrame({'Name' : [], 'Id' : []})
i=0
for tournament in tournaments_df.index:
    addition = add_players(tournament, tournaments_df)
    if addition is None:
        continue
    players_df = pd.concat([players_df, addition], axis = 0)
    print(i)
    i += 1
players_df = players_df.drop_duplicates().reset_index(drop=True).set_index('Name')
players_df

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679

                     Id
Name
Agustin Calleri    C478
Alex Calatrava     C361
Antony Dupuis      D272
Arnaud Clement     C487
Cedric Pioline     P226
...                 ...
Zhao Zhao          Z09X
Bohua Dong         D0F0
Chukang Wang       WB36
Robert Strombachs  S0GV
Ye Cong Mo         M0BW

[3328 rows x 1 columns]

In [ ]:
matches_df = pd.DataFrame({'Player 1' : [], 'Player 2' : [], 'Winner' : [], 'Tournament Name' : []})
i=0
for index in tournaments_df.index:
    addition = collect_tourney_data(index, tournaments_df)
    if addition is None:
        continue
    matches_df = pd.concat([matches_df,addition], axis = 0)
    print(i)
    i+=1
matches_df = matches_df.reset_index().drop('index', axis = 1)
matches_df['Year'] = matches_df['Year'].astype('int64')
matches_df = matches_df.drop_duplicates().reset_index(drop=True)

https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2002/results
0
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2002/results
1
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2003/results
2
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2004/results
3
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2005/results
4
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2006/results
5
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2007/results
6
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2008/results
7
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2009/results
8
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2010/results
9
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2011/results
10
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2012/results
11
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2013/results
12
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2014/results
13
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2015/results
14
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2016/results
15
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2017/results
16
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2018/results
17
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2019/results
18
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2020/results
19
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2021/results
20
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2022/results
21
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2023/results
22
https://www.atptour.com/en/scores/archive/'s-hertogenbosch/440/2024/results
23
https://www.atptour.com/en/scores/archive/acapulco/807/2001/results
24
https://www.atptour.com/en/scores/archive/acapulco/807/2002/results
25
https://www.atptour.com/en/scores/archive/acapulco/807/2003/results
26
https://www.atptour.com/en/scores/archive/acapulco/807/2004/results
27
https://www.atptour.com/en/scores/archive/acapulco/807/2005/results
28
https://www.atptour.com/en/scores/archive/acapulco/807/2006/results
29
https://www.atptour.com/en/scores/archive/acapulco/807/2007/results
30
https://www.atptour.com/en/scores/archive/acapulco/807/2008/results
31
https://www.atptour.com/en/scores/archive/acapulco/807/2009/results
32
https://www.atptour.com/en/scores/archive/acapulco/807/2010/results
33
https://www.atptour.com/en/scores/archive/acapulco/807/2011/results
34
https://www.atptour.com/en/scores/archive/acapulco/807/2012/results
35
https://www.atptour.com/en/scores/archive/acapulco/807/2013/results
36
https://www.atptour.com/en/scores/archive/acapulco/807/2014/results
37
https://www.atptour.com/en/scores/archive/acapulco/807/2015/results
38
https://www.atptour.com/en/scores/archive/acapulco/807/2016/results
39
https://www.atptour.com/en/scores/archive/acapulco/807/2017/results
40
https://www.atptour.com/en/scores/archive/acapulco/807/2018/results
41
https://www.atptour.com/en/scores/archive/acapulco/807/2019/results
42
https://www.atptour.com/en/scores/archive/acapulco/807/2020/results
43
https://www.atptour.com/en/scores/archive/acapulco/807/2021/results
44
https://www.atptour.com/en/scores/archive/acapulco/807/2022/results
45
https://www.atptour.com/en/scores/archive/acapulco/807/2023/results
46
https://www.atptour.com/en/scores/archive/acapulco/807/2024/results
47
https://www.atptour.com/en/scores/archive/adelaide/7308/2001/results
48
https://www.atptour.com/en/scores/archive/adelaide/7308/2002/results
49
https://www.atptour.com/en/scores/archive/adelaide/7308/2003/results
50
https://www.atptour.com/en/scores/archive/adelaide/7308/2004/results
51
https://www.atptour.com/en/scores/archive/adelaide/7308/2005/results
52
https://www.atptour.com/en/scores/archive/adelaide/7308/2006/results
53
https://www.atptour.com/en/scores/archive/adelaide/7308/2007/results
54
https://www.atptour.com/en/scores/archive/adelaide/7308/2008/results
55
https://www.atptour.com/en/scores/archive/adelaide/8998/2020/results
56
https://www.atptour.com/en/scores/archive/adelaide/8998/2024/results
57
https://www.atptour.com/en/scores/archive/adelaide 1/8998/2022/results
58
https://www.atptour.com/en/scores/archive/adelaide 1/2843/2023/results
59
https://www.atptour.com/en/scores/archive/adelaide 2/9667/2022/results
60
https://www.atptour.com/en/scores/archive/adelaide 2/8998/2023/results
61
https://www.atptour.com/en/scores/archive/almaty/9410/2024/results
62
https://www.atptour.com/en/scores/archive/amersfoort/317/2002/results
63
https://www.atptour.com/en/scores/archive/amersfoort/317/2003/results
64
https://www.atptour.com/en/scores/archive/amersfoort/317/2004/results
65
https://www.atptour.com/en/scores/archive/amersfoort/317/2005/results
66
https://www.atptour.com/en/scores/archive/amersfoort/317/2006/results
67
https://www.atptour.com/en/scores/archive/amersfoort/317/2007/results
68
https://www.atptour.com/en/scores/archive/amersfoort/317/2008/results
69
https://www.atptour.com/en/scores/archive/amsterdam/317/2001/results
70
https://www.atptour.com/en/scores/archive/antalya/7650/2017/results
71
https://www.atptour.com/en/scores/archive/antalya/7650/2018/results
72
https://www.atptour.com/en/scores/archive/antalya/7650/2019/results
73
https://www.atptour.com/en/scores/archive/antalya/9426/2021/results
74
https://www.atptour.com/en/scores/archive/antwerp/7485/2016/results
75
https://www.atptour.com/en/scores/archive/antwerp/7485/2017/results
76
https://www.atptour.com/en/scores/archive/antwerp/7485/2018/results
77
https://www.atptour.com/en/scores/archive/antwerp/7485/2019/results
78
https://www.atptour.com/en/scores/archive/antwerp/7485/2020/results
79
https://www.atptour.com/en/scores/archive/antwerp/7485/2021/results
80
https://www.atptour.com/en/scores/archive/antwerp/7485/2022/results
81
https://www.atptour.com/en/scores/archive/antwerp/7485/2023/results
82
https://www.atptour.com/en/scores/archive/antwerp/7485/2024/results
83
https://www.atptour.com/en/scores/archive/astana/9410/2022/results
84
https://www.atptour.com/en/scores/archive/astana/9410/2023/results
85
https://www.atptour.com/en/scores/archive/athens olympics/96/2004/results
86
https://www.atptour.com/en/scores/archive/atlanta/409/2001/results
87
https://www.atptour.com/en/scores/archive/atlanta/6116/2010/results
88
https://www.atptour.com/en/scores/archive/atlanta/6116/2011/results
89
https://www.atptour.com/en/scores/archive/atlanta/6116/2012/results
90
https://www.atptour.com/en/scores/archive/atlanta/6116/2013/results
91
https://www.atptour.com/en/scores/archive/atlanta/6116/2014/results
92
https://www.atptour.com/en/scores/archive/atlanta/6116/2015/results
93
https://www.atptour.com/en/scores/archive/atlanta/6116/2016/results
94
https://www.atptour.com/en/scores/archive/atlanta/6116/2017/results
95
https://www.atptour.com/en/scores/archive/atlanta/6116/2018/results
96
https://www.atptour.com/en/scores/archive/atlanta/6116/2019/results
97
https://www.atptour.com/en/scores/archive/atlanta/6116/2020/results
98
https://www.atptour.com/en/scores/archive/atlanta/6116/2021/results
99
https://www.atptour.com/en/scores/archive/atlanta/6116/2022/results
100
https://www.atptour.com/en/scores/archive/atlanta/6116/2023/results
101
https://www.atptour.com/en/scores/archive/atlanta/6116/2024/results
102
https://www.atptour.com/en/scores/archive/atp cup/8888/2020/results
103
https://www.atptour.com/en/scores/archive/atp cup/8888/2021/results
104
https://www.atptour.com/en/scores/archive/atp cup/8888/2022/results
105
https://www.atptour.com/en/scores/archive/atp finals/605/2009/results
106
https://www.atptour.com/en/scores/archive/atp finals/605/2010/results
107
https://www.atptour.com/en/scores/archive/atp finals/605/2011/results
108
https://www.atptour.com/en/scores/archive/atp finals/605/2012/results
109
https://www.atptour.com/en/scores/archive/atp finals/605/2013/results
110
https://www.atptour.com/en/scores/archive/atp finals/605/2014/results
111
https://www.atptour.com/en/scores/archive/atp finals/605/2015/results
112
https://www.atptour.com/en/scores/archive/atp finals/605/2016/results
113
https://www.atptour.com/en/scores/archive/atp tour world doubles championship/602/2002/results
114
https://www.atptour.com/en/scores/archive/auckland/301/2002/results
115
https://www.atptour.com/en/scores/archive/auckland/301/2002/results
116
https://www.atptour.com/en/scores/archive/auckland/301/2003/results
117
https://www.atptour.com/en/scores/archive/auckland/301/2004/results
118
https://www.atptour.com/en/scores/archive/auckland/301/2005/results
119
https://www.atptour.com/en/scores/archive/auckland/301/2006/results
120
https://www.atptour.com/en/scores/archive/auckland/301/2007/results
121
https://www.atptour.com/en/scores/archive/auckland/301/2008/results
122
https://www.atptour.com/en/scores/archive/auckland/301/2009/results
123
https://www.atptour.com/en/scores/archive/auckland/301/2010/results
124
https://www.atptour.com/en/scores/archive/auckland/301/2011/results
125
https://www.atptour.com/en/scores/archive/auckland/301/2012/results
126
https://www.atptour.com/en/scores/archive/auckland/301/2013/results
127
https://www.atptour.com/en/scores/archive/auckland/301/2014/results
128
https://www.atptour.com/en/scores/archive/auckland/301/2015/results
129
https://www.atptour.com/en/scores/archive/auckland/301/2016/results
130
https://www.atptour.com/en/scores/archive/auckland/301/2017/results
131
https://www.atptour.com/en/scores/archive/auckland/301/2018/results
132
https://www.atptour.com/en/scores/archive/auckland/301/2019/results
133
https://www.atptour.com/en/scores/archive/auckland/301/2020/results
134
https://www.atptour.com/en/scores/archive/auckland/301/2021/results
135
https://www.atptour.com/en/scores/archive/auckland/301/2023/results
136
https://www.atptour.com/en/scores/archive/auckland/301/2024/results
137
https://www.atptour.com/en/scores/archive/australian open/580/2002/results
138
https://www.atptour.com/en/scores/archive/australian open/580/2002/results
139
https://www.atptour.com/en/scores/archive/australian open/580/2003/results
140
https://www.atptour.com/en/scores/archive/australian open/580/2004/results
141
https://www.atptour.com/en/scores/archive/australian open/580/2005/results
142
https://www.atptour.com/en/scores/archive/australian open/580/2006/results
143
https://www.atptour.com/en/scores/archive/australian open/580/2007/results
144
https://www.atptour.com/en/scores/archive/australian open/580/2008/results
145
https://www.atptour.com/en/scores/archive/australian open/580/2009/results
146
https://www.atptour.com/en/scores/archive/australian open/580/2010/results
147
https://www.atptour.com/en/scores/archive/australian open/580/2011/results
148
https://www.atptour.com/en/scores/archive/australian open/580/2012/results
149
https://www.atptour.com/en/scores/archive/australian open/580/2013/results
150
https://www.atptour.com/en/scores/archive/australian open/580/2014/results
151
https://www.atptour.com/en/scores/archive/australian open/580/2015/results
152
https://www.atptour.com/en/scores/archive/australian open/580/2016/results
153
https://www.atptour.com/en/scores/archive/australian open/580/2017/results
154
https://www.atptour.com/en/scores/archive/australian open/580/2018/results
155
https://www.atptour.com/en/scores/archive/australian open/580/2019/results
156
https://www.atptour.com/en/scores/archive/australian open/580/2020/results
157
https://www.atptour.com/en/scores/archive/australian open/580/2021/results
158
https://www.atptour.com/en/scores/archive/australian open/580/2022/results
159
https://www.atptour.com/en/scores/archive/australian open/580/2023/results
160
https://www.atptour.com/en/scores/archive/australian open/580/2024/results
161
https://www.atptour.com/en/scores/archive/bangkok/1720/2003/results
162
https://www.atptour.com/en/scores/archive/bangkok/1720/2004/results
163
https://www.atptour.com/en/scores/archive/bangkok/1720/2005/results
164
https://www.atptour.com/en/scores/archive/bangkok/1720/2006/results
165
https://www.atptour.com/en/scores/archive/bangkok/1720/2007/results
166
https://www.atptour.com/en/scores/archive/bangkok/1720/2008/results
167
https://www.atptour.com/en/scores/archive/bangkok/1720/2009/results
168
https://www.atptour.com/en/scores/archive/bangkok/1720/2010/results
169
https://www.atptour.com/en/scores/archive/bangkok/1720/2011/results
170
https://www.atptour.com/en/scores/archive/bangkok/1720/2012/results
171
https://www.atptour.com/en/scores/archive/bangkok/1720/2013/results
172
https://www.atptour.com/en/scores/archive/banja luka/2841/2023/results
173
https://www.atptour.com/en/scores/archive/barcelona/425/2002/results
174
https://www.atptour.com/en/scores/archive/barcelona/425/2002/results
175
https://www.atptour.com/en/scores/archive/barcelona/425/2003/results
176
https://www.atptour.com/en/scores/archive/barcelona/425/2004/results
177
https://www.atptour.com/en/scores/archive/barcelona/425/2005/results
178
https://www.atptour.com/en/scores/archive/barcelona/425/2006/results
179
https://www.atptour.com/en/scores/archive/barcelona/425/2007/results
180
https://www.atptour.com/en/scores/archive/barcelona/425/2008/results
181
https://www.atptour.com/en/scores/archive/barcelona/425/2009/results
182
https://www.atptour.com/en/scores/archive/barcelona/425/2010/results
183
https://www.atptour.com/en/scores/archive/barcelona/425/2011/results
184
https://www.atptour.com/en/scores/archive/barcelona/425/2012/results
185
https://www.atptour.com/en/scores/archive/barcelona/425/2013/results
186
https://www.atptour.com/en/scores/archive/barcelona/425/2014/results
187
https://www.atptour.com/en/scores/archive/barcelona/425/2015/results
188
https://www.atptour.com/en/scores/archive/barcelona/425/2016/results
189
https://www.atptour.com/en/scores/archive/barcelona/425/2017/results
190
https://www.atptour.com/en/scores/archive/barcelona/425/2018/results
191
https://www.atptour.com/en/scores/archive/barcelona/425/2019/results
192
https://www.atptour.com/en/scores/archive/barcelona/425/2020/results
193
https://www.atptour.com/en/scores/archive/barcelona/425/2021/results
194
https://www.atptour.com/en/scores/archive/barcelona/425/2022/results
195
https://www.atptour.com/en/scores/archive/barcelona/425/2023/results
196
https://www.atptour.com/en/scores/archive/barcelona/425/2024/results
197
https://www.atptour.com/en/scores/archive/basel/328/2002/results
198
https://www.atptour.com/en/scores/archive/basel/328/2002/results
199
https://www.atptour.com/en/scores/archive/basel/328/2003/results
200
https://www.atptour.com/en/scores/archive/basel/328/2004/results
201
https://www.atptour.com/en/scores/archive/basel/328/2005/results
202
https://www.atptour.com/en/scores/archive/basel/328/2006/results
203
https://www.atptour.com/en/scores/archive/basel/328/2007/results
204
https://www.atptour.com/en/scores/archive/basel/328/2008/results
205
https://www.atptour.com/en/scores/archive/basel/328/2009/results
206
https://www.atptour.com/en/scores/archive/basel/328/2010/results
207
https://www.atptour.com/en/scores/archive/basel/328/2011/results
208
https://www.atptour.com/en/scores/archive/basel/328/2012/results
209
https://www.atptour.com/en/scores/archive/basel/328/2013/results
210
https://www.atptour.com/en/scores/archive/basel/328/2014/results
211
https://www.atptour.com/en/scores/archive/basel/328/2015/results
212
https://www.atptour.com/en/scores/archive/basel/328/2016/results
213
https://www.atptour.com/en/scores/archive/basel/328/2017/results
214
https://www.atptour.com/en/scores/archive/basel/328/2018/results
215
https://www.atptour.com/en/scores/archive/basel/328/2019/results
216
https://www.atptour.com/en/scores/archive/basel/328/2020/results
217
https://www.atptour.com/en/scores/archive/basel/328/2021/results
218
https://www.atptour.com/en/scores/archive/basel/328/2022/results
219
https://www.atptour.com/en/scores/archive/basel/328/2023/results
220
https://www.atptour.com/en/scores/archive/basel/328/2024/results
221
https://www.atptour.com/en/scores/archive/bastad/316/2002/results
222
https://www.atptour.com/en/scores/archive/bastad/316/2002/results
223
https://www.atptour.com/en/scores/archive/bastad/316/2003/results
224
https://www.atptour.com/en/scores/archive/bastad/316/2004/results
225
https://www.atptour.com/en/scores/archive/bastad/316/2005/results
226
https://www.atptour.com/en/scores/archive/bastad/316/2006/results
227
https://www.atptour.com/en/scores/archive/bastad/316/2007/results
228
https://www.atptour.com/en/scores/archive/bastad/316/2008/results
229
https://www.atptour.com/en/scores/archive/bastad/316/2009/results
230
https://www.atptour.com/en/scores/archive/bastad/316/2010/results
231
https://www.atptour.com/en/scores/archive/bastad/316/2011/results
232
https://www.atptour.com/en/scores/archive/bastad/316/2012/results
233
https://www.atptour.com/en/scores/archive/bastad/316/2013/results
234
https://www.atptour.com/en/scores/archive/bastad/316/2014/results
235
https://www.atptour.com/en/scores/archive/bastad/316/2015/results
236
https://www.atptour.com/en/scores/archive/bastad/316/2016/results
237
https://www.atptour.com/en/scores/archive/bastad/316/2017/results
238
https://www.atptour.com/en/scores/archive/bastad/316/2018/results
239
https://www.atptour.com/en/scores/archive/bastad/316/2019/results
240
https://www.atptour.com/en/scores/archive/bastad/316/2020/results
241
https://www.atptour.com/en/scores/archive/bastad/316/2021/results
242
https://www.atptour.com/en/scores/archive/bastad/316/2022/results
243
https://www.atptour.com/en/scores/archive/bastad/316/2023/results
244
https://www.atptour.com/en/scores/archive/bastad/316/2024/results
245
https://www.atptour.com/en/scores/archive/beijing/747/2004/results
246
https://www.atptour.com/en/scores/archive/beijing/747/2005/results
247
https://www.atptour.com/en/scores/archive/beijing/747/2006/results
248
https://www.atptour.com/en/scores/archive/beijing/747/2007/results
249
https://www.atptour.com/en/scores/archive/beijing/747/2008/results
250
https://www.atptour.com/en/scores/archive/beijing/747/2009/results
251
https://www.atptour.com/en/scores/archive/beijing/747/2010/results
252
https://www.atptour.com/en/scores/archive/beijing/747/2011/results
253
https://www.atptour.com/en/scores/archive/beijing/747/2012/results
254
https://www.atptour.com/en/scores/archive/beijing/747/2013/results
255
https://www.atptour.com/en/scores/archive/beijing/747/2014/results
256
https://www.atptour.com/en/scores/archive/beijing/747/2015/results
257
https://www.atptour.com/en/scores/archive/beijing/747/2016/results
258
https://www.atptour.com/en/scores/archive/beijing/747/2017/results
259
https://www.atptour.com/en/scores/archive/beijing/747/2018/results
260
https://www.atptour.com/en/scores/archive/beijing/747/2019/results
261
https://www.atptour.com/en/scores/archive/beijing/747/2020/results
262
https://www.atptour.com/en/scores/archive/beijing/747/2021/results
263
https://www.atptour.com/en/scores/archive/beijing/747/2023/results
264
https://www.atptour.com/en/scores/archive/beijing/747/2024/results
265
https://www.atptour.com/en/scores/archive/beijing olympics/96/2008/results
266
https://www.atptour.com/en/scores/archive/belgrade/5053/2009/results
267
https://www.atptour.com/en/scores/archive/belgrade/5053/2010/results
268
https://www.atptour.com/en/scores/archive/belgrade/5053/2011/results
269
https://www.atptour.com/en/scores/archive/belgrade/5053/2012/results
270
https://www.atptour.com/en/scores/archive/belgrade/5053/2022/results
271
https://www.atptour.com/en/scores/archive/belgrade/4787/2024/results
272
https://www.atptour.com/en/scores/archive/belgrade 1/5053/2021/results
273

In [ ]:
matches_df

,Player 1,Player 2,Winner,Tournament Name,Year
0,Sjeng Schalken,Arnaud Clement,Sjeng Schalken,'S-Hertogenbosch,2002
1,Arnaud Clement,Guillermo Canas,Arnaud Clement,'S-Hertogenbosch,2002
2,Sjeng Schalken,Tommy Robredo,Sjeng Schalken,'S-Hertogenbosch,2002
3,Arnaud Clement,Lleyton Hewitt,Arnaud Clement,'S-Hertogenbosch,2002
4,Sjeng Schalken,Roger Federer,Sjeng Schalken,'S-Hertogenbosch,2002
...,...,...,...,...,...
95569,Alex Bolt,Lorenzo Giustino,Alex Bolt,Zhuhai,2023
95570,Dominik Palan,Chukang Wang,Dominik Palan,Zhuhai,2023
95571,Arthur Weber,Robert Strombachs,Arthur Weber,Zhuhai,2023
95572,Luke Saville,Stefanos Sakellaridis,Luke Saville,Zhuhai,2023
95573,Antoine Bellier,Colin Sinclair,Antoine Bellier,Zhuhai,2023

In [30]:
import importlib
import scraping_functions
importlib.reload(scraping_functions)
from scraping_functions import *
matches_df = pd.read_csv('../Data/Staging/matches.csv')
tournaments_df = pd.read_csv('../Data/Staging/tournaments.csv').drop_duplicates().set_index(['Name', 'Year'])
players_df = pd.read_csv('../Data/Staging/players.csv').set_index('Name')
for index, row in matches_df.iterrows():
    player1_ranking = await find_ranking(row, tournaments_df, players_df, player1 = True)
    print(player1_ranking)
    #matches_df.at[index, 'Player 1 Ranking'] = find_ranking(row, tournaments_df, players_df, player1 = True)
    #matches_df.at[index, 'Player 2 Ranking'] = find_ranking(row, tournaments_df, players_df, player1 = False)
    #print(index, print(find_ranking(row, tournaments_df, players_df, player1 = True), find_ranking(row, tournaments_df, players_df, player1 = False)))
    break

2002-06-17
https://www.atptour.com/en/players/sjeng-schalken/S572/rankings-history?year=all
Ranking items loaded!
Date         | Rank | Points
-------------------------------
2007/02/05 |  N/A | 677
2007/01/29 |  N/A | 677
2007/01/22 |  N/A | 676
2007/01/15 |  N/A | 676
2007/01/08 |  N/A | 676
2007/01/01 |  N/A | 675
2006/12/25 |  N/A | 678
2006/12/18 |  N/A | 678
2006/12/11 |  N/A | 679
2006/12/04 |  N/A | 677
2006/11/27 |  N/A | 675
2006/11/20 |  N/A | 681
2006/11/13 |  N/A | 687
2006/11/06 |  N/A | 687
2006/10/30 |  N/A | 687
2006/10/23 |  N/A | 685
2006/10/16 |  N/A | 683
2006/10/09 |  N/A | 686
2006/10/02 |  N/A | 686
2006/09/25 |  N/A | 679
2006/09/18 |  N/A | 675
2006/09/11 |  N/A | 676
2006/09/04 |  N/A | 670
2006/08/28 |  N/A | 670
2006/08/21 |  N/A | 670
2006/08/14 |  N/A | 666
2006/08/07 |  N/A | 657
2006/07/31 |  N/A | 659
2006/07/24 |  N/A | 652
2006/07/17 |  N/A | 611
2006/07/10 |  N/A | 610
2006/07/03 |  N/A | 614
2006/06/26 |  N/A | 614
2006/06/19 |  N/A | 603
2006/06/12 |  N/A | 503
2006/06/05 |  N/A | 511
2006/05/29 |  N/A | 511
2006/05/22 |  N/A | 511
2006/05/15 |  N/A | 447
2006/05/08 |  N/A | 445
2006/05/01 |  N/A | 443
2006/04/24 |  N/A | 382
2006/04/17 |  N/A | 386
2006/04/10 |  N/A | 384
2006/04/03 |  N/A | 382
2006/03/27 |  N/A | 381
2006/03/20 |  N/A | 381
2006/03/13 |  N/A | 378
2006/03/06 |  N/A | 378
2006/02/27 |  N/A | 374
2006/02/20 |  N/A | 376
2006/02/13 |  N/A | 303
2006/02/06 |  N/A | 268
2006/01/30 |  N/A | 252
2006/01/23 |  N/A | 243
2006/01/16 |  N/A | 243
2006/01/09 |  N/A | 233
2006/01/02 |  N/A | 230
2005/12/26 |  N/A | 230
2005/12/19 |  N/A | 230
2005/12/12 |  N/A | 230
2005/12/05 |  N/A | 230
2005/11/28 |  N/A | 231
2005/11/21 |  N/A | 230
2005/11/14 |  N/A | 234
2005/11/07 |  N/A | 234
2005/10/31 |  N/A | 231
2005/10/24 |  N/A | 229
2005/10/17 |  N/A | 222
2005/10/10 |  N/A | 222
2005/10/03 |  N/A | 227
2005/09/26 |  N/A | 229
2005/09/19 |  N/A | 229
2005/09/12 |  N/A | 231
2005/09/05 |  N/A | 233
2005/08/29 |  N/A | 233
2005/08/22 |  N/A | 233
2005/08/15 |  N/A | 229
2005/08/08 |  N/A | 232
2005/08/01 |  N/A | 200
2005/07/25 |  N/A | 201
2005/07/18 |  N/A | 202
2005/07/11 |  N/A | 202
2005/07/04 |  N/A | 201
2005/06/27 |  N/A | 89
2005/06/20 |  N/A | 89
2005/06/13 |  N/A | 89
2005/06/06 |  N/A | 87
2005/05/30 |  N/A | 88
2005/05/23 |  N/A | 88
2005/05/16 |  N/A | 92
2005/05/09 |  N/A | 93
2005/05/02 |  N/A | 82
2005/04/25 |  N/A | 85
2005/04/18 |  N/A | 87
2005/04/11 |  N/A | 84
2005/04/04 |  N/A | 82
2005/03/28 |  N/A | 81
2005/03/21 |  N/A | 81
2005/03/14 |  N/A | 79
2005/03/07 |  N/A | 79
2005/02/28 |  N/A | 73
2005/02/21 |  N/A | 70
2005/02/14 |  N/A | 70
2005/02/07 |  N/A | 76
2005/01/31 |  N/A | 79
2005/01/24 |  N/A | 61
2005/01/17 |  N/A | 61
2005/01/10 |  N/A | 60
2005/01/03 |  N/A | 57
2004/12/27 |  N/A | 57
2004/12/20 |  N/A | 57
2004/12/13 |  N/A | 57
2004/12/06 |  N/A | 57
2004/11/29 |  N/A | 57
2004/11/22 |  N/A | 57
2004/11/15 |  N/A | 57
2004/11/08 |  N/A | 57
2004/11/01 |  N/A | 54
2004/10/25 |  N/A | 54
2004/10/18 |  N/A | 55
2004/10/11 |  N/A | 55
2004/10/04 |  N/A | 52
2004/09/27 |  N/A | 52
2004/09/20 |  N/A | 52
2004/09/13 |  N/A | 50
2004/09/06 |  N/A | 27
2004/08/30 |  N/A | 27
2004/08/23 |  N/A | 27
2004/08/16 |  N/A | 25
2004/08/09 |  N/A | 24
2004/08/02 |  N/A | 25
2004/07/26 |  N/A | 24
2004/07/19 |  N/A | 21
2004/07/12 |  N/A | 22
2004/07/05 |  N/A | 23
2004/06/28 |  N/A | 23
2004/06/21 |  N/A | 23
2004/06/14 |  N/A | 17
2004/06/07 |  N/A | 16
2004/05/31 |  N/A | 15
2004/05/24 |  N/A | 15
2004/05/17 |  N/A | 15
2004/05/10 |  N/A | 16
2004/05/03 |  N/A | 16
2004/04/26 |  N/A | 14
2004/04/19 |  N/A | 14
2004/04/12 |  N/A | 14
2004/04/05 |  N/A | 14
2004/03/29 |  N/A | 14
2004/03/22 |  N/A | 14
2004/03/15 |  N/A | 15
2004/03/08 |  N/A | 15
2004/03/01 |  N/A | 15
2004/02/23 |  N/A | 15
2004/02/16 |  N/A | 15
2004/02/09 |  N/A | 15
2004/02/02 |  N/A | 15
2004/01/26 |  N/A | 17
2004/01/19 |  N/A | 17
2004/01/12 |  N/A | 16
2004/01/05 |  N/A | 18
2003/12/29 |  N/A | 18
2003/12/22 |  N/A | 18
2003/12/15 |  N/A | 18
2003/12/08 |  N/A | 18
2003/12/01 |  N/A | 18
2003/11/24 |  N/A | 18
2003/11/17 |  N/A | 18
2003/11/10 |  N/A | 19
2003/11/03 |  N/A | 19
2003/10/27 |  N/A | 13
2003/10/20 |  N/A | 14
2003/10/13 |  N/A | 14
2003/10/06 |  N/A | 14
2003/09/29 |  N/A | 13
2003/09/22 |  N/A | 13
2003/09/15 |  N/A | 13
2003/09/08 |  N/A | 13
2003/09/01 |  N/A | 12
2003/08/25 |  N/A | 12
2003/08/18 |  N/A | 12
2003/08/11 |  N/A | 12
2003/08/04 |  N/A | 11
2003/07/28 |  N/A | 12
2003/07/21 |  N/A | 12
2003/07/14 |  N/A | 12
2003/07/07 |  N/A | 12
2003/06/30 |  N/A | 12
2003/06/23 |  N/A | 12
2003/06/16 |  N/A | 12
2003/06/09 |  N/A | 12
2003/06/02 |  N/A | 13
2003/05/26 |  N/A | 13
2003/05/19 |  N/A | 13
2003/05/12 |  N/A | 12
2003/05/05 |  N/A | 11
2003/04/28 |  N/A | 11
2003/04/21 |  N/A | 11
2003/04/14 |  N/A | 14
2003/04/07 |  N/A | 14
2003/03/31 |  N/A | 14
2003/03/24 |  N/A | 14
2003/03/17 |  N/A | 14
2003/03/10 |  N/A | 14
2003/03/03 |  N/A | 14
2003/02/24 |  N/A | 15
2003/02/17 |  N/A | 19
2003/02/10 |  N/A | 19
2003/02/03 |  N/A | 19
2003/01/27 |  N/A | 17
2003/01/20 |  N/A | 20
2003/01/13 |  N/A | 20
2003/01/06 |  N/A | 20
2002/12/30 |  N/A | 20
2002/12/23 |  N/A | 20
2002/12/16 |  N/A | 20
2002/12/09 |  N/A | 20
2002/12/02 |  N/A | 20
2002/11/25 |  N/A | 20
2002/11/18 |  N/A | 20
2002/11/11 |  N/A | 20
2002/11/04 |  N/A | 20
2002/10/28 |  N/A | 19
2002/10/21 |  N/A | 15
2002/10/14 |  N/A | 15
2002/10/07 |  N/A | 16
2002/09/30 |  N/A | 17
2002/09/23 |  N/A | 17
2002/09/16 |  N/A | 17
2002/09/09 |  N/A | 17
2002/09/02 |  N/A | 25
2002/08/26 |  N/A | 25
2002/08/19 |  N/A | 24
2002/08/12 |  N/A | 18
2002/08/05 |  N/A | 20
2002/07/29 |  N/A | 22
2002/07/22 |  N/A | 23
2002/07/15 |  N/A | 22
2002/07/08 |  N/A | 22
2002/07/01 |  N/A | 23
2002/06/24 |  N/A | 23
2002/06/17 |  N/A | 31
2002/06/10 |  N/A | 34
2002/06/03 |  N/A | 33
2002/05/27 |  N/A | 33
2002/05/20 |  N/A | 33
2002/05/13 |  N/A | 34
2002/05/06 |  N/A | 34
2002/04/29 |  N/A | 33
2002/04/22 |  N/A | 34
2002/04/15 |  N/A | 31
2002/04/08 |  N/A | 31
2002/04/01 |  N/A | 31
2002/03/25 |  N/A | 30
2002/03/18 |  N/A | 30
2002/03/11 |  N/A | 28
2002/03/04 |  N/A | 28
2002/02/25 |  N/A | 28
2002/02/18 |  N/A | 28
2002/02/11 |  N/A | 28
2002/02/04 |  N/A | 28
2002/01/28 |  N/A | 27
2002/01/21 |  N/A | 30
2002/01/14 |  N/A | 30
2002/01/07 |  N/A | 29
2001/12/31 |  N/A | 26
2001/12/24 |  N/A | 26
2001/12/17 |  N/A | 26
2001/12/10 |  N/A | 26
2001/12/03 |  N/A | 26
2001/11/26 |  N/A | 26
2001/11/19 |  N/A | 26
2001/11/12 |  N/A | 26
2001/11/05 |  N/A | 26
2001/10/29 |  N/A | 25
2001/10/22 |  N/A | 40
2001/10/15 |  N/A | 32
2001/10/08 |  N/A | 23
2001/10/01 |  N/A | 24
2001/09/24 |  N/A | 24
2001/09/17 |  N/A | 24
2001/09/10 |  N/A | 23
2001/09/03 |  N/A | 24
2001/08/27 |  N/A | 24
2001/08/20 |  N/A | 24
2001/08/13 |  N/A | 33
2001/08/06 |  N/A | 32
2001/07/30 |  N/A | 29
2001/07/23 |  N/A | 27
2001/07/16 |  N/A | 32
2001/07/09 |  N/A | 32
2001/07/02 |  N/A | 28
2001/06/25 |  N/A | 28
2001/06/18 |  N/A | 28
2001/06/11 |  N/A | 29
2001/06/04 |  N/A | 31
2001/05/28 |  N/A | 31
2001/05/21 |  N/A | 32
2001/05/14 |  N/A | 30
2001/05/07 |  N/A | 30
2001/04/30 |  N/A | 29
2001/04/23 |  N/A | 29
2001/04/16 |  N/A | 30
2001/04/09 |  N/A | 31
2001/04/02 |  N/A | 31
2001/03/26 |  N/A | 33
2001/03/19 |  N/A | 33
2001/03/12 |  N/A | 29
2001/03/05 |  N/A | 29
2001/02/26 |  N/A | 28
2001/02/19 |  N/A | 27
2001/02/12 |  N/A | 28
2001/02/05 |  N/A | 29
2001/01/29 |  N/A | 28
2001/01/22 |  N/A | 27
2001/01/15 |  N/A | 27
2001/01/08 |  N/A | 25
2001/01/01 |  N/A | 22
2000/12/25 |  N/A | 22
2000/12/18 |  N/A | 22
2000/12/11 |  N/A | 22
2000/12/04 |  N/A | 22
2000/11/27 |  N/A | 22
2000/11/20 |  N/A | 25
2000/11/13 |  N/A | 26
2000/11/06 |  N/A | 27
2000/10/30 |  N/A | 29
2000/10/23 |  N/A | 25
2000/10/16 |  N/A | 34
2000/10/09 |  N/A | 51
2000/10/02 |  N/A | 54
2000/09/25 |  N/A | 52
2000/09/18 |  N/A | 52
2000/09/11 |  N/A | 52
2000/09/04 |  N/A | 58
2000/08/28 |  N/A | 58
2000/08/21 |  N/A | 53
2000/08/14 |  N/A | 53
2000/08/07 |  N/A | 52
2000/07/31 |  N/A | 52
2000/07/24 |  N/A | 53
2000/07/17 |  N/A | 52
2000/07/10 |  N/A | 52
2000/07/03 |  N/A | 53
2000/06/26 |  N/A | 53
2000/06/19 |  N/A | 52
2000/06/12 |  N/A | 50
2000/06/05 |  N/A | 39
2000/05/29 |  N/A | 39
2000/05/22 |  N/A | 39
2000/05/15 |  N/A | 44
2000/05/08 |  N/A | 44
2000/05/01 |  N/A | 40
2000/04/24 |  N/A | 43
2000/04/17 |  N/A | 50
2000/04/10 |  N/A | 46
2000/04/03 |  N/A | 47
2000/03/27 |  N/A | 49
2000/03/20 |  N/A | 49
2000/03/13 |  N/A | 64
2000/03/06 |  N/A | 54
2000/02/28 |  N/A | 51
2000/02/21 |  N/A | 51
2000/02/14 |  N/A | 50
2000/02/07 |  N/A | 49
2000/01/31 |  N/A | 51
2000/01/24 |  N/A | 47
2000/01/17 |  N/A | 47
2000/01/10 |  N/A | 37
1999/12/27 |  N/A | 44
1999/12/20 |  N/A | 44
1999/12/13 |  N/A | 44
1999/12/06 |  N/A | 44
1999/11/29 |  N/A | 45
1999/11/22 |  N/A | 46
1999/11/15 |  N/A | 44
1999/11/08 |  N/A | 43
1999/11/01 |  N/A | 49
1999/10/25 |  N/A | 55
1999/10/18 |  N/A | 54
1999/10/11 |  N/A | 44
1999/10/04 |  N/A | 41
1999/09/27 |  N/A | 43
1999/09/20 |  N/A | 43
1999/09/13 |  N/A | 42
1999/09/06 |  N/A | 45
1999/08/30 |  N/A | 45
1999/08/23 |  N/A | 51
1999/08/16 |  N/A | 49
1999/08/09 |  N/A | 47
1999/08/02 |  N/A | 47
1999/07/26 |  N/A | 46
1999/07/19 |  N/A | 44
1999/07/12 |  N/A | 44
1999/07/05 |  N/A | 44
1999/06/28 |  N/A | 50
1999/06/21 |  N/A | 50
1999/06/14 |  N/A | 46
1999/06/07 |  N/A | 53
1999/05/31 |  N/A | 63
1999/05/24 |  N/A | 63
1999/05/17 |  N/A | 57
1999/05/10 |  N/A | 56
1999/05/03 |  N/A | 53
1999/04/26 |  N/A | 53
1999/04/19 |  N/A | 52
1999/04/12 |  N/A | 55
1999/04/05 |  N/A | 56
1999/03/29 |  N/A | 56
1999/03/22 |  N/A | 54
1999/03/15 |  N/A | 54
1999/03/08 |  N/A | 64
1999/03/01 |  N/A | 51
1999/02/22 |  N/A | 49
1999/02/15 |  N/A | 47
1999/02/08 |  N/A | 45
1999/02/01 |  N/A | 46
1999/01/25 |  N/A | 49
1999/01/18 |  N/A | 49
1999/01/11 |  N/A | 74
1999/01/04 |  N/A | 66
1998/12/28 |  N/A | 66
1998/12/21 |  N/A | 66
1998/12/14 |  N/A | 66
1998/12/07 |  N/A | 67
1998/11/30 |  N/A | 67
1998/11/23 |  N/A | 67
1998/11/16 |  N/A | 68
1998/11/09 |  N/A | 68
1998/11/02 |  N/A | 67
1998/10/26 |  N/A | 66
1998/10/19 |  N/A | 67
1998/10/12 |  N/A | 80
1998/10/05 |  N/A | 80
1998/09/28 |  N/A | 80
1998/09/21 |  N/A | 81
1998/09/14 |  N/A | 81
1998/09/07 |  N/A | 81
1998/08/31 |  N/A | 81
1998/08/24 |  N/A | 86
1998/08/17 |  N/A | 54
1998/08/10 |  N/A | 52
1998/08/03 |  N/A | 49
1998/07/27 |  N/A | 50
1998/07/20 |  N/A | 51
1998/07/13 |  N/A | 51
1998/07/06 |  N/A | 52
1998/06/29 |  N/A | 53
1998/06/22 |  N/A | 53
1998/06/15 |  N/A | 55
1998/06/08 |  N/A | 52
1998/06/01 |  N/A | 54
1998/05/25 |  N/A | 54
1998/05/18 |  N/A | 51
1998/05/11 |  N/A | 57
1998/05/04 |  N/A | 61
1998/04/27 |  N/A | 61
1998/04/20 |  N/A | 61
1998/04/13 |  N/A | 60
1998/04/06 |  N/A | 60
1998/03/30 |  N/A | 60
1998/03/23 |  N/A | 59
1998/03/16 |  N/A | 59
1998/03/09 |  N/A | 56
1998/03/02 |  N/A | 65
1998/02/23 |  N/A | 55
1998/02/16 |  N/A | 57
1998/02/09 |  N/A | 57
1998/02/02 |  N/A | 54
1998/01/26 |  N/A | 52
1998/01/19 |  N/A | 52
1998/01/12 |  N/A | 51
1998/01/05 |  N/A | 59
1997/12/29 |  N/A | 59
1997/12/22 |  N/A | 59
1997/12/15 |  N/A | 59
1997/12/08 |  N/A | 59
1997/12/01 |  N/A | 59
1997/11/24 |  N/A | 59
1997/11/17 |  N/A | 60
1997/11/10 |  N/A | 59
1997/11/03 |  N/A | 54
1997/10/27 |  N/A | 53
1997/10/20 |  N/A | 54
1997/10/13 |  N/A | 57
1997/10/06 |  N/A | 60
1997/09/29 |  N/A | 60
1997/09/22 |  N/A | 60
1997/09/15 |  N/A | 59
1997/09/08 |  N/A | 51
1997/09/01 |  N/A | 47
1997/08/25 |  N/A | 47
1997/08/18 |  N/A | 79
1997/08/11 |  N/A | 82
1997/08/04 |  N/A | 85
1997/07/28 |  N/A | 85
1997/07/21 |  N/A | 83
1997/07/14 |  N/A | 82
1997/07/07 |  N/A | 81
1997/06/30 |  N/A | 79
1997/06/23 |  N/A | 79
1997/06/16 |  N/A | 81
1997/06/09 |  N/A | 80
1997/06/02 |  N/A | 75
1997/05/26 |  N/A | 75
1997/05/19 |  N/A | 81
1997/05/12 |  N/A | 81
1997/05/05 |  N/A | 87
1997/04/28 |  N/A | 85
1997/04/21 |  N/A | 67
1997/04/14 |  N/A | 66
1997/04/07 |  N/A | 68
1997/03/31 |  N/A | 68
1997/03/24 |  N/A | 68
1997/03/17 |  N/A | 68
1997/03/10 |  N/A | 69
1997/03/03 |  N/A | 66
1997/02/24 |  N/A | 88
1997/02/17 |  N/A | 86
1997/02/10 |  N/A | 88
1997/02/03 |  N/A | 88
1997/01/27 |  N/A | 88
1997/01/20 |  N/A | 85
1997/01/13 |  N/A | 85
1997/01/06 |  N/A | 67
1996/12/30 |  N/A | 65
1996/12/23 |  N/A | 65
1996/12/16 |  N/A | 65
1996/12/09 |  N/A | 65
1996/12/02 |  N/A | 65
1996/11/25 |  N/A | 65
1996/11/18 |  N/A | 66
1996/11/11 |  N/A | 66
1996/11/04 |  N/A | 73
1996/10/28 |  N/A | 74
1996/10/21 |  N/A | 71
1996/10/14 |  N/A | 73
1996/10/07 |  N/A | 73
1996/09/30 |  N/A | 48
1996/09/23 |  N/A | 44
1996/09/16 |  N/A | 43
1996/09/09 |  N/A | 45
1996/09/02 |  N/A | 48
1996/08/26 |  N/A | 48
1996/08/19 |  N/A | 49
1996/08/12 |  N/A | 51
1996/08/05 |  N/A | 50
1996/07/29 |  N/A | 51
1996/07/22 |  N/A | 52
1996/07/15 |  N/A | 54
1996/07/08 |  N/A | 57
1996/07/01 |  N/A | 56
1996/06/24 |  N/A | 56
1996/06/17 |  N/A | 53
1996/06/10 |  N/A | 57
1996/06/03 |  N/A | 63
1996/05/27 |  N/A | 63
1996/05/20 |  N/A | 61
1996/05/13 |  N/A | 67
1996/05/06 |  N/A | 63
1996/04/29 |  N/A | 52
1996/04/22 |  N/A | 65
1996/04/15 |  N/A | 60
1996/04/08 |  N/A | 62
1996/04/01 |  N/A | 62
1996/03/25 |  N/A | 53
1996/03/18 |  N/A | 53
1996/03/11 |  N/A | 53
1996/03/04 |  N/A | 51
1996/02/26 |  N/A | 50
1996/02/19 |  N/A | 48
1996/02/12 |  N/A | 45
1996/02/05 |  N/A | 47
1996/01/29 |  N/A | 46
1996/01/22 |  N/A | 45
1996/01/15 |  N/A | 45
1996/01/08 |  N/A | 69
1996/01/01 |  N/A | 69
1995/12/25 |  N/A | 69
1995/12/18 |  N/A | 69
1995/12/11 |  N/A | 67
1995/12/04 |  N/A | 67
1995/11/27 |  N/A | 67
1995/11/20 |  N/A | 54
1995/11/13 |  N/A | 55
1995/11/06 |  N/A | 53
1995/10/30 |  N/A | 55
1995/10/23 |  N/A | 56
1995/10/16 |  N/A | 46
1995/10/09 |  N/A | 44
1995/10/02 |  N/A | 69
1995/09/25 |  N/A | 77
1995/09/18 |  N/A | 81
1995/09/11 |  N/A | 81
1995/09/04 |  N/A | 86
1995/08/28 |  N/A | 86
1995/08/21 |  N/A | 88
1995/08/14 |  N/A | 88
1995/08/07 |  N/A | 87
1995/07/31 |  N/A | 88
1995/07/24 |  N/A | 86
1995/07/17 |  N/A | 86
1995/07/10 |  N/A | 82
1995/07/03 |  N/A | 84
1995/06/26 |  N/A | 84
1995/06/19 |  N/A | 84
1995/06/12 |  N/A | 85
1995/06/05 |  N/A | 87
1995/05/29 |  N/A | 87
1995/05/22 |  N/A | 87
1995/05/15 |  N/A | 85
1995/05/08 |  N/A | 84
1995/05/01 |  N/A | 98
1995/04/24 |  N/A | 101
1995/04/17 |  N/A | 115
1995/04/10 |  N/A | 115
1995/04/03 |  N/A | 118
1995/03/27 |  N/A | 121
1995/03/20 |  N/A | 135
1995/03/13 |  N/A | 135
1995/03/06 |  N/A | 134
1995/02/27 |  N/A | 138
1995/02/20 |  N/A | 140
1995/02/13 |  N/A | 140
1995/02/06 |  N/A | 143
1995/01/30 |  N/A | 147
1995/01/23 |  N/A | 148
1995/01/16 |  N/A | 148
1995/01/09 |  N/A | 147
1995/01/02 |  N/A | 148
1994/12/26 |  N/A | 148
1994/12/19 |  N/A | 148
1994/12/12 |  N/A | 146
1994/12/05 |  N/A | 153
1994/11/28 |  N/A | 153
1994/11/21 |  N/A | 187
1994/11/14 |  N/A | 195
1994/11/07 |  N/A | 195
1994/10/31 |  N/A | 197
1994/10/24 |  N/A | 177
1994/10/17 |  N/A | 234
1994/10/10 |  N/A | 242
1994/10/03 |  N/A | 250
1994/09/26 |  N/A | 273
1994/09/19 |  N/A | 274
1994/09/12 |  N/A | 269
1994/09/05 |  N/A | 267
1994/08/29 |  N/A | 267
1994/08/22 |  N/A | 267
1994/08/15 |  N/A | 266
1994/08/08 |  N/A | 266
1994/08/01 |  N/A | 269
1994/07/25 |  N/A | 281
1994/07/18 |  N/A | 285
1994/07/11 |  N/A | 292
1994/07/04 |  N/A | 296
1994/06/27 |  N/A | 292
1994/06/20 |  N/A | 292
1994/06/13 |  N/A | 293
1994/06/06 |  N/A | 330
1994/05/30 |  N/A | 333
1994/05/23 |  N/A | 333
1994/05/16 |  N/A | 326
1994/05/09 |  N/A | 326
1994/05/02 |  N/A | 324
1994/04/25 |  N/A | 322
1994/04/18 |  N/A | 321
1994/04/11 |  N/A | 318
1994/04/04 |  N/A | 319
1994/03/28 |  N/A | 323
1994/03/21 |  N/A | 321
1994/03/14 |  N/A | 319
1994/03/07 |  N/A | 319
1994/02/28 |  N/A | 436
1994/02/21 |  N/A | 438
1994/02/14 |  N/A | 439
1994/02/07 |  N/A | 436
1994/01/31 |  N/A | 438
1994/01/24 |  N/A | 444
1994/01/17 |  N/A | 444
1994/01/10 |  N/A | 443
1994/01/03 |  N/A | 442
1993/12/27 |  N/A | 442
1993/12/20 |  N/A | 442
1993/12/13 |  N/A | 440
1993/12/06 |  N/A | 437
1993/11/29 |  N/A | 468
1993/11/22 |  N/A | 464
1993/11/15 |  N/A | 464
1993/11/08 |  N/A | 466
1993/11/01 |  N/A | 467
1993/10/25 |  N/A | 796
1993/10/18 |  N/A | 794
1993/10/11 |  N/A | 784
1993/10/04 |  N/A | 778
1993/09/27 |  N/A | 782
1993/09/20 |  N/A | 743
1993/09/13 |  N/A | 735
1993/09/06 |  N/A | 737
1993/08/30 |  N/A | 737
1993/08/23 |  N/A | 736
1993/08/16 |  N/A | 740
1993/08/09 |  N/A | 726
1993/08/02 |  N/A | 723
1993/07/26 |  N/A | 719
1993/07/19 |  N/A | 714
1993/07/12 |  N/A | 1012
1993/07/05 |  N/A | 989
1993/06/28 |  N/A | 995
1993/06/21 |  N/A | 995
1993/06/14 |  N/A | 992
1993/06/07 |  N/A | 1000
1993/05/31 |  N/A | 991
1993/05/24 |  N/A | 991
1993/05/17 |  N/A | 991
1993/05/10 |  N/A | 988
1993/05/03 |  N/A | 990
1993/04/26 |  N/A | 987
1993/04/19 |  N/A | 979
1993/04/12 |  N/A | 969
1993/04/05 |  N/A | 968
1993/03/29 |  N/A | 961
1993/03/22 |  N/A | 961
1993/03/15 |  N/A | 966
1993/03/08 |  N/A | 966
1993/03/01 |  N/A | 959
1993/02/22 |  N/A | 955
1993/02/15 |  N/A | 959
1993/02/08 |  N/A | 958
1993/02/01 |  N/A | 959
1993/01/25 |  N/A | 951
1993/01/18 |  N/A | 951
1993/01/11 |  N/A | 950
1993/01/04 |  N/A | 947
1992/12/28 |  N/A | 947
1992/12/21 |  N/A | 947
1992/12/14 |  N/A | 958
1992/12/07 |  N/A | 958
1992/11/30 |  N/A | 944
1992/11/23 |  N/A | 953
1992/11/16 |  N/A | 960
1992/11/09 |  N/A | 961
1992/11/02 |  N/A | 960
1992/10/26 |  N/A | 956
1992/10/19 |  N/A | 961
1992/10/12 |  N/A | 964
1992/10/05 |  N/A | 964
1992/09/28 |  N/A | 957
2007/02/05 |  N/A | 0
2007/01/29 |  N/A | 0
2007/01/22 |  N/A | 0
2007/01/15 |  N/A | 0
2007/01/08 |  N/A | 0
2007/01/01 |  N/A | 0
2006/12/25 |  N/A | 0
2006/12/18 |  N/A | 0
2006/12/11 |  N/A | 0
2006/12/04 |  N/A | 0
2006/11/27 |  N/A | 0
2006/11/20 |  N/A | 0
2006/11/13 |  N/A | 0
2006/11/06 |  N/A | 0
2006/10/30 |  N/A | 0
2006/10/23 |  N/A | 0
2006/10/16 |  N/A | 0
2006/10/09 |  N/A | 0
2006/10/02 |  N/A | 0
2006/09/25 |  N/A | 0
2006/09/18 |  N/A | 0
2006/09/11 |  N/A | 0
2006/09/04 |  N/A | 0
2006/08/28 |  N/A | 0
2006/08/21 |  N/A | 0
2006/08/14 |  N/A | 0
2006/08/07 |  N/A | 0
2006/07/31 |  N/A | 0
2006/07/24 |  N/A | 0
2006/07/17 |  N/A | 0
2006/07/10 |  N/A | 0
2006/07/03 |  N/A | 0
2006/06/26 |  N/A | 0
2006/06/19 |  N/A | 0
2006/06/12 |  N/A | 0
2006/06/05 |  N/A | 0
2006/05/29 |  N/A | 0
2006/05/22 |  N/A | 0
2006/05/15 |  N/A | 0
2006/05/08 |  N/A | 0
2006/05/01 |  N/A | 0
2006/04/24 |  N/A | 0
2006/04/17 |  N/A | 0
2006/04/10 |  N/A | 0
2006/04/03 |  N/A | 0
2006/03/27 |  N/A | 0
2006/03/20 |  N/A | 0
2006/03/13 |  N/A | 0
2006/03/06 |  N/A | 0
2006/02/27 |  N/A | 0
2006/02/20 |  N/A | 0
2006/02/13 |  N/A | 0
2006/02/06 |  N/A | 0
2006/01/30 |  N/A | 0
2006/01/23 |  N/A | 0
2006/01/16 |  N/A | 0
2006/01/09 |  N/A | 0
2006/01/02 |  N/A | 0
2005/12/26 |  N/A | 0
2005/12/19 |  N/A | 0
2005/12/12 |  N/A | 0
2005/12/05 |  N/A | 0
2005/11/28 |  N/A | 0
2005/11/21 |  N/A | 0
2005/11/14 |  N/A | 0
2005/11/07 |  N/A | 0
2005/10/31 |  N/A | 0
2005/10/24 |  N/A | 0
2005/10/17 |  N/A | 0
2005/10/10 |  N/A | 0
2005/10/03 |  N/A | 0
2005/09/26 |  N/A | 0
2005/09/19 |  N/A | 0
2005/09/12 |  N/A | 0
2005/09/05 |  N/A | 0
2005/08/29 |  N/A | 0
2005/08/22 |  N/A | 0
2005/08/15 |  N/A | 0
2005/08/08 |  N/A | 0
2005/08/01 |  N/A | 0
2005/07/25 |  N/A | 0
2005/07/18 |  N/A | 0
2005/07/11 |  N/A | 0
2005/07/04 |  N/A | 0
2005/06/27 |  N/A | 0
2005/06/20 |  N/A | 0
2005/06/13 |  N/A | 0
2005/06/06 |  N/A | 0
2005/05/30 |  N/A | 0
2005/05/23 |  N/A | 0
2005/05/16 |  N/A | 0
2005/05/09 |  N/A | 0
2005/05/02 |  N/A | 0
2005/04/25 |  N/A | 0
2005/04/18 |  N/A | 0
2005/04/11 |  N/A | 0
2005/04/04 |  N/A | 0
2005/03/28 |  N/A | 0
2005/03/21 |  N/A | 0
2005/03/14 |  N/A | 0
2005/03/07 |  N/A | 0
2005/02/28 |  N/A | 1461
2005/02/21 |  N/A | 1461
2005/02/14 |  N/A | 1457
2005/02/07 |  N/A | 1451
2005/01/31 |  N/A | 1440
2005/01/24 |  N/A | 0

C:\Users\aman0\AppData\Local\Temp\ipykernel_13164\2843184238.py:9: RuntimeWarning: coroutine 'find_ranking' was never awaited
  player1_ranking = await find_ranking(row, tournaments_df, players_df, player1 = True)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from bs4 import BeautifulSoup

# Setup Chrome in headless mode
options = Options()
options.add_argument("--headless")
driver = webdriver.Chrome(options=options)

try:
    url = "https://www.atptour.com/en/players/sjeng-schalken/S572/rankings-history?year=all"
    driver.get(url)

    # Wait for the rankings table items to load
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "div.ranking-item"))
    )

    print("Ranking items loaded!")

    # Get page source after JS execution
    html = driver.page_source

    # Parse with BeautifulSoup
    soup = BeautifulSoup(html, "html.parser")
    ranking_items = soup.select("div.ranking-item")

    print("Date         | Rank | Points")
    print("-------------------------------")

    for item in ranking_items:
        type_ = item.select_one("dd.type")
        if type_ and type_.get_text(strip=True) != "Singles":
            continue  # Skip doubles

        date = item.select_one("dd.name span")
        rank = item.select_one("dd.rank div")
        points = item.select_one("dd.points div.set-points div")

        date_text = date.get_text(strip=True) if date else "N/A"
        rank_text = rank.get_text(strip=True) if rank else "N/A"
        points_text = points.get_text(strip=True) if points else "N/A"

        print(f"{date_text} | {rank_text:>4} | {points_text}")

except Exception as e:
    print("Error:", e)
finally:
    driver.quit()

Ranking items loaded!
Date         | Rank | Points
-------------------------------
2007/02/05 |  N/A | 677
2007/01/29 |  N/A | 677
2007/01/22 |  N/A | 676
2007/01/15 |  N/A | 676
2007/01/08 |  N/A | 676
2007/01/01 |  N/A | 675
2006/12/25 |  N/A | 678
2006/12/18 |  N/A | 678
2006/12/11 |  N/A | 679
2006/12/04 |  N/A | 677
2006/11/27 |  N/A | 675
2006/11/20 |  N/A | 681
2006/11/13 |  N/A | 687
2006/11/06 |  N/A | 687
2006/10/30 |  N/A | 687
2006/10/23 |  N/A | 685
2006/10/16 |  N/A | 683
2006/10/09 |  N/A | 686
2006/10/02 |  N/A | 686
2006/09/25 |  N/A | 679
2006/09/18 |  N/A | 675
2006/09/11 |  N/A | 676
2006/09/04 |  N/A | 670
2006/08/28 |  N/A | 670
2006/08/21 |  N/A | 670
2006/08/14 |  N/A | 666
2006/08/07 |  N/A | 657
2006/07/31 |  N/A | 659
2006/07/24 |  N/A | 652
2006/07/17 |  N/A | 611
2006/07/10 |  N/A | 610
2006/07/03 |  N/A | 614
2006/06/26 |  N/A | 614
2006/06/19 |  N/A | 603
2006/06/12 |  N/A | 503
2006/06/05 |  N/A | 511
2006/05/29 |  N/A | 511
2006/05/22 |  N/A | 511
2006/05/15 |  N/A | 447
2006/05/08 |  N/A | 445
2006/05/01 |  N/A | 443
2006/04/24 |  N/A | 382
2006/04/17 |  N/A | 386
2006/04/10 |  N/A | 384
2006/04/03 |  N/A | 382
2006/03/27 |  N/A | 381
2006/03/20 |  N/A | 381
2006/03/13 |  N/A | 378
2006/03/06 |  N/A | 378
2006/02/27 |  N/A | 374
2006/02/20 |  N/A | 376
2006/02/13 |  N/A | 303
2006/02/06 |  N/A | 268
2006/01/30 |  N/A | 252
2006/01/23 |  N/A | 243
2006/01/16 |  N/A | 243
2006/01/09 |  N/A | 233
2006/01/02 |  N/A | 230
2005/12/26 |  N/A | 230
2005/12/19 |  N/A | 230
2005/12/12 |  N/A | 230
2005/12/05 |  N/A | 230
2005/11/28 |  N/A | 231
2005/11/21 |  N/A | 230
2005/11/14 |  N/A | 234
2005/11/07 |  N/A | 234
2005/10/31 |  N/A | 231
2005/10/24 |  N/A | 229
2005/10/17 |  N/A | 222
2005/10/10 |  N/A | 222
2005/10/03 |  N/A | 227
2005/09/26 |  N/A | 229
2005/09/19 |  N/A | 229
2005/09/12 |  N/A | 231
2005/09/05 |  N/A | 233
2005/08/29 |  N/A | 233
2005/08/22 |  N/A | 233
2005/08/15 |  N/A | 229
2005/08/08 |  N/A | 232
2005/08/01 |  N/A | 200
2005/07/25 |  N/A | 201
2005/07/18 |  N/A | 202
2005/07/11 |  N/A | 202
2005/07/04 |  N/A | 201
2005/06/27 |  N/A | 89
2005/06/20 |  N/A | 89
2005/06/13 |  N/A | 89
2005/06/06 |  N/A | 87
2005/05/30 |  N/A | 88
2005/05/23 |  N/A | 88
2005/05/16 |  N/A | 92
2005/05/09 |  N/A | 93
2005/05/02 |  N/A | 82
2005/04/25 |  N/A | 85
2005/04/18 |  N/A | 87
2005/04/11 |  N/A | 84
2005/04/04 |  N/A | 82
2005/03/28 |  N/A | 81
2005/03/21 |  N/A | 81
2005/03/14 |  N/A | 79
2005/03/07 |  N/A | 79
2005/02/28 |  N/A | 73
2005/02/21 |  N/A | 70
2005/02/14 |  N/A | 70
2005/02/07 |  N/A | 76
2005/01/31 |  N/A | 79
2005/01/24 |  N/A | 61
2005/01/17 |  N/A | 61
2005/01/10 |  N/A | 60
2005/01/03 |  N/A | 57
2004/12/27 |  N/A | 57
2004/12/20 |  N/A | 57
2004/12/13 |  N/A | 57
2004/12/06 |  N/A | 57
2004/11/29 |  N/A | 57
2004/11/22 |  N/A | 57
2004/11/15 |  N/A | 57
2004/11/08 |  N/A | 57
2004/11/01 |  N/A | 54
2004/10/25 |  N/A | 54
2004/10/18 |  N/A | 55
2004/10/11 |  N/A | 55
2004/10/04 |  N/A | 52
2004/09/27 |  N/A | 52
2004/09/20 |  N/A | 52
2004/09/13 |  N/A | 50
2004/09/06 |  N/A | 27
2004/08/30 |  N/A | 27
2004/08/23 |  N/A | 27
2004/08/16 |  N/A | 25
2004/08/09 |  N/A | 24
2004/08/02 |  N/A | 25
2004/07/26 |  N/A | 24
2004/07/19 |  N/A | 21
2004/07/12 |  N/A | 22
2004/07/05 |  N/A | 23
2004/06/28 |  N/A | 23
2004/06/21 |  N/A | 23
2004/06/14 |  N/A | 17
2004/06/07 |  N/A | 16
2004/05/31 |  N/A | 15
2004/05/24 |  N/A | 15
2004/05/17 |  N/A | 15
2004/05/10 |  N/A | 16
2004/05/03 |  N/A | 16
2004/04/26 |  N/A | 14
2004/04/19 |  N/A | 14
2004/04/12 |  N/A | 14
2004/04/05 |  N/A | 14
2004/03/29 |  N/A | 14
2004/03/22 |  N/A | 14
2004/03/15 |  N/A | 15
2004/03/08 |  N/A | 15
2004/03/01 |  N/A | 15
2004/02/23 |  N/A | 15
2004/02/16 |  N/A | 15
2004/02/09 |  N/A | 15
2004/02/02 |  N/A | 15
2004/01/26 |  N/A | 17
2004/01/19 |  N/A | 17
2004/01/12 |  N/A | 16
2004/01/05 |  N/A | 18
2003/12/29 |  N/A | 18
2003/12/22 |  N/A | 18
2003/12/15 |  N/A | 18
2003/12/08 |  N/A | 18
2003/12/01 |  N/A | 18
2003/11/24 |  N/A | 18
2003/11/17 |  N/A | 18
2003/11/10 |  N/A | 19
2003/11/03 |  N/A | 19
2003/10/27 |  N/A | 13
2003/10/20 |  N/A | 14
2003/10/13 |  N/A | 14
2003/10/06 |  N/A | 14
2003/09/29 |  N/A | 13
2003/09/22 |  N/A | 13
2003/09/15 |  N/A | 13
2003/09/08 |  N/A | 13
2003/09/01 |  N/A | 12
2003/08/25 |  N/A | 12
2003/08/18 |  N/A | 12
2003/08/11 |  N/A | 12
2003/08/04 |  N/A | 11
2003/07/28 |  N/A | 12
2003/07/21 |  N/A | 12
2003/07/14 |  N/A | 12
2003/07/07 |  N/A | 12
2003/06/30 |  N/A | 12
2003/06/23 |  N/A | 12
2003/06/16 |  N/A | 12
2003/06/09 |  N/A | 12
2003/06/02 |  N/A | 13
2003/05/26 |  N/A | 13
2003/05/19 |  N/A | 13
2003/05/12 |  N/A | 12
2003/05/05 |  N/A | 11
2003/04/28 |  N/A | 11
2003/04/21 |  N/A | 11
2003/04/14 |  N/A | 14
2003/04/07 |  N/A | 14
2003/03/31 |  N/A | 14
2003/03/24 |  N/A | 14
2003/03/17 |  N/A | 14
2003/03/10 |  N/A | 14
2003/03/03 |  N/A | 14
2003/02/24 |  N/A | 15
2003/02/17 |  N/A | 19
2003/02/10 |  N/A | 19
2003/02/03 |  N/A | 19
2003/01/27 |  N/A | 17
2003/01/20 |  N/A | 20
2003/01/13 |  N/A | 20
2003/01/06 |  N/A | 20
2002/12/30 |  N/A | 20
2002/12/23 |  N/A | 20
2002/12/16 |  N/A | 20
2002/12/09 |  N/A | 20
2002/12/02 |  N/A | 20
2002/11/25 |  N/A | 20
2002/11/18 |  N/A | 20
2002/11/11 |  N/A | 20
2002/11/04 |  N/A | 20
2002/10/28 |  N/A | 19
2002/10/21 |  N/A | 15
2002/10/14 |  N/A | 15
2002/10/07 |  N/A | 16
2002/09/30 |  N/A | 17
2002/09/23 |  N/A | 17
2002/09/16 |  N/A | 17
2002/09/09 |  N/A | 17
2002/09/02 |  N/A | 25
2002/08/26 |  N/A | 25
2002/08/19 |  N/A | 24
2002/08/12 |  N/A | 18
2002/08/05 |  N/A | 20
2002/07/29 |  N/A | 22
2002/07/22 |  N/A | 23
2002/07/15 |  N/A | 22
2002/07/08 |  N/A | 22
2002/07/01 |  N/A | 23
2002/06/24 |  N/A | 23
2002/06/17 |  N/A | 31
2002/06/10 |  N/A | 34
2002/06/03 |  N/A | 33
2002/05/27 |  N/A | 33
2002/05/20 |  N/A | 33
2002/05/13 |  N/A | 34
2002/05/06 |  N/A | 34
2002/04/29 |  N/A | 33
2002/04/22 |  N/A | 34
2002/04/15 |  N/A | 31
2002/04/08 |  N/A | 31
2002/04/01 |  N/A | 31
2002/03/25 |  N/A | 30
2002/03/18 |  N/A | 30
2002/03/11 |  N/A | 28
2002/03/04 |  N/A | 28
2002/02/25 |  N/A | 28
2002/02/18 |  N/A | 28
2002/02/11 |  N/A | 28
2002/02/04 |  N/A | 28
2002/01/28 |  N/A | 27
2002/01/21 |  N/A | 30
2002/01/14 |  N/A | 30
2002/01/07 |  N/A | 29
2001/12/31 |  N/A | 26
2001/12/24 |  N/A | 26
2001/12/17 |  N/A | 26
2001/12/10 |  N/A | 26
2001/12/03 |  N/A | 26
2001/11/26 |  N/A | 26
2001/11/19 |  N/A | 26
2001/11/12 |  N/A | 26
2001/11/05 |  N/A | 26
2001/10/29 |  N/A | 25
2001/10/22 |  N/A | 40
2001/10/15 |  N/A | 32
2001/10/08 |  N/A | 23
2001/10/01 |  N/A | 24
2001/09/24 |  N/A | 24
2001/09/17 |  N/A | 24
2001/09/10 |  N/A | 23
2001/09/03 |  N/A | 24
2001/08/27 |  N/A | 24
2001/08/20 |  N/A | 24
2001/08/13 |  N/A | 33
2001/08/06 |  N/A | 32
2001/07/30 |  N/A | 29
2001/07/23 |  N/A | 27
2001/07/16 |  N/A | 32
2001/07/09 |  N/A | 32
2001/07/02 |  N/A | 28
2001/06/25 |  N/A | 28
2001/06/18 |  N/A | 28
2001/06/11 |  N/A | 29
2001/06/04 |  N/A | 31
2001/05/28 |  N/A | 31
2001/05/21 |  N/A | 32
2001/05/14 |  N/A | 30
2001/05/07 |  N/A | 30
2001/04/30 |  N/A | 29
2001/04/23 |  N/A | 29
2001/04/16 |  N/A | 30
2001/04/09 |  N/A | 31
2001/04/02 |  N/A | 31
2001/03/26 |  N/A | 33
2001/03/19 |  N/A | 33
2001/03/12 |  N/A | 29
2001/03/05 |  N/A | 29
2001/02/26 |  N/A | 28
2001/02/19 |  N/A | 27
2001/02/12 |  N/A | 28
2001/02/05 |  N/A | 29
2001/01/29 |  N/A | 28
2001/01/22 |  N/A | 27
2001/01/15 |  N/A | 27
2001/01/08 |  N/A | 25
2001/01/01 |  N/A | 22
2000/12/25 |  N/A | 22
2000/12/18 |  N/A | 22
2000/12/11 |  N/A | 22
2000/12/04 |  N/A | 22
2000/11/27 |  N/A | 22
2000/11/20 |  N/A | 25
2000/11/13 |  N/A | 26
2000/11/06 |  N/A | 27
2000/10/30 |  N/A | 29
2000/10/23 |  N/A | 25
2000/10/16 |  N/A | 34
2000/10/09 |  N/A | 51
2000/10/02 |  N/A | 54
2000/09/25 |  N/A | 52
2000/09/18 |  N/A | 52
2000/09/11 |  N/A | 52
2000/09/04 |  N/A | 58
2000/08/28 |  N/A | 58
2000/08/21 |  N/A | 53
2000/08/14 |  N/A | 53
2000/08/07 |  N/A | 52
2000/07/31 |  N/A | 52
2000/07/24 |  N/A | 53
2000/07/17 |  N/A | 52
2000/07/10 |  N/A | 52
2000/07/03 |  N/A | 53
2000/06/26 |  N/A | 53
2000/06/19 |  N/A | 52
2000/06/12 |  N/A | 50
2000/06/05 |  N/A | 39
2000/05/29 |  N/A | 39
2000/05/22 |  N/A | 39
2000/05/15 |  N/A | 44
2000/05/08 |  N/A | 44
2000/05/01 |  N/A | 40
2000/04/24 |  N/A | 43
2000/04/17 |  N/A | 50
2000/04/10 |  N/A | 46
2000/04/03 |  N/A | 47
2000/03/27 |  N/A | 49
2000/03/20 |  N/A | 49
2000/03/13 |  N/A | 64
2000/03/06 |  N/A | 54
2000/02/28 |  N/A | 51
2000/02/21 |  N/A | 51
2000/02/14 |  N/A | 50
2000/02/07 |  N/A | 49
2000/01/31 |  N/A | 51
2000/01/24 |  N/A | 47
2000/01/17 |  N/A | 47
2000/01/10 |  N/A | 37
1999/12/27 |  N/A | 44
1999/12/20 |  N/A | 44
1999/12/13 |  N/A | 44
1999/12/06 |  N/A | 44
1999/11/29 |  N/A | 45
1999/11/22 |  N/A | 46
1999/11/15 |  N/A | 44
1999/11/08 |  N/A | 43
1999/11/01 |  N/A | 49
1999/10/25 |  N/A | 55
1999/10/18 |  N/A | 54
1999/10/11 |  N/A | 44
1999/10/04 |  N/A | 41
1999/09/27 |  N/A | 43
1999/09/20 |  N/A | 43
1999/09/13 |  N/A | 42
1999/09/06 |  N/A | 45
1999/08/30 |  N/A | 45
1999/08/23 |  N/A | 51
1999/08/16 |  N/A | 49
1999/08/09 |  N/A | 47
1999/08/02 |  N/A | 47
1999/07/26 |  N/A | 46
1999/07/19 |  N/A | 44
1999/07/12 |  N/A | 44
1999/07/05 |  N/A | 44
1999/06/28 |  N/A | 50
1999/06/21 |  N/A | 50
1999/06/14 |  N/A | 46
1999/06/07 |  N/A | 53
1999/05/31 |  N/A | 63
1999/05/24 |  N/A | 63
1999/05/17 |  N/A | 57
1999/05/10 |  N/A | 56
1999/05/03 |  N/A | 53
1999/04/26 |  N/A | 53
1999/04/19 |  N/A | 52
1999/04/12 |  N/A | 55
1999/04/05 |  N/A | 56
1999/03/29 |  N/A | 56
1999/03/22 |  N/A | 54
1999/03/15 |  N/A | 54
1999/03/08 |  N/A | 64
1999/03/01 |  N/A | 51
1999/02/22 |  N/A | 49
1999/02/15 |  N/A | 47
1999/02/08 |  N/A | 45
1999/02/01 |  N/A | 46
1999/01/25 |  N/A | 49
1999/01/18 |  N/A | 49
1999/01/11 |  N/A | 74
1999/01/04 |  N/A | 66
1998/12/28 |  N/A | 66
1998/12/21 |  N/A | 66
1998/12/14 |  N/A | 66
1998/12/07 |  N/A | 67
1998/11/30 |  N/A | 67
1998/11/23 |  N/A | 67
1998/11/16 |  N/A | 68
1998/11/09 |  N/A | 68
1998/11/02 |  N/A | 67
1998/10/26 |  N/A | 66
1998/10/19 |  N/A | 67
1998/10/12 |  N/A | 80
1998/10/05 |  N/A | 80
1998/09/28 |  N/A | 80
1998/09/21 |  N/A | 81
1998/09/14 |  N/A | 81
1998/09/07 |  N/A | 81
1998/08/31 |  N/A | 81
1998/08/24 |  N/A | 86
1998/08/17 |  N/A | 54
1998/08/10 |  N/A | 52
1998/08/03 |  N/A | 49
1998/07/27 |  N/A | 50
1998/07/20 |  N/A | 51
1998/07/13 |  N/A | 51
1998/07/06 |  N/A | 52
1998/06/29 |  N/A | 53
1998/06/22 |  N/A | 53
1998/06/15 |  N/A | 55
1998/06/08 |  N/A | 52
1998/06/01 |  N/A | 54
1998/05/25 |  N/A | 54
1998/05/18 |  N/A | 51
1998/05/11 |  N/A | 57
1998/05/04 |  N/A | 61
1998/04/27 |  N/A | 61
1998/04/20 |  N/A | 61
1998/04/13 |  N/A | 60
1998/04/06 |  N/A | 60
1998/03/30 |  N/A | 60
1998/03/23 |  N/A | 59
1998/03/16 |  N/A | 59
1998/03/09 |  N/A | 56
1998/03/02 |  N/A | 65
1998/02/23 |  N/A | 55
1998/02/16 |  N/A | 57
1998/02/09 |  N/A | 57
1998/02/02 |  N/A | 54
1998/01/26 |  N/A | 52
1998/01/19 |  N/A | 52
1998/01/12 |  N/A | 51
1998/01/05 |  N/A | 59
1997/12/29 |  N/A | 59
1997/12/22 |  N/A | 59
1997/12/15 |  N/A | 59
1997/12/08 |  N/A | 59
1997/12/01 |  N/A | 59
1997/11/24 |  N/A | 59
1997/11/17 |  N/A | 60
1997/11/10 |  N/A | 59
1997/11/03 |  N/A | 54
1997/10/27 |  N/A | 53
1997/10/20 |  N/A | 54
1997/10/13 |  N/A | 57
1997/10/06 |  N/A | 60
1997/09/29 |  N/A | 60
1997/09/22 |  N/A | 60
1997/09/15 |  N/A | 59
1997/09/08 |  N/A | 51
1997/09/01 |  N/A | 47
1997/08/25 |  N/A | 47
1997/08/18 |  N/A | 79
1997/08/11 |  N/A | 82
1997/08/04 |  N/A | 85
1997/07/28 |  N/A | 85
1997/07/21 |  N/A | 83
1997/07/14 |  N/A | 82
1997/07/07 |  N/A | 81
1997/06/30 |  N/A | 79
1997/06/23 |  N/A | 79
1997/06/16 |  N/A | 81
1997/06/09 |  N/A | 80
1997/06/02 |  N/A | 75
1997/05/26 |  N/A | 75
1997/05/19 |  N/A | 81
1997/05/12 |  N/A | 81
1997/05/05 |  N/A | 87
1997/04/28 |  N/A | 85
1997/04/21 |  N/A | 67
1997/04/14 |  N/A | 66
1997/04/07 |  N/A | 68
1997/03/31 |  N/A | 68
1997/03/24 |  N/A | 68
1997/03/17 |  N/A | 68
1997/03/10 |  N/A | 69
1997/03/03 |  N/A | 66
1997/02/24 |  N/A | 88
1997/02/17 |  N/A | 86
1997/02/10 |  N/A | 88
1997/02/03 |  N/A | 88
1997/01/27 |  N/A | 88
1997/01/20 |  N/A | 85
1997/01/13 |  N/A | 85
1997/01/06 |  N/A | 67
1996/12/30 |  N/A | 65
1996/12/23 |  N/A | 65
1996/12/16 |  N/A | 65
1996/12/09 |  N/A | 65
1996/12/02 |  N/A | 65
1996/11/25 |  N/A | 65
1996/11/18 |  N/A | 66
1996/11/11 |  N/A | 66
1996/11/04 |  N/A | 73
1996/10/28 |  N/A | 74
1996/10/21 |  N/A | 71
1996/10/14 |  N/A | 73
1996/10/07 |  N/A | 73
1996/09/30 |  N/A | 48
1996/09/23 |  N/A | 44
1996/09/16 |  N/A | 43
1996/09/09 |  N/A | 45
1996/09/02 |  N/A | 48
1996/08/26 |  N/A | 48
1996/08/19 |  N/A | 49
1996/08/12 |  N/A | 51
1996/08/05 |  N/A | 50
1996/07/29 |  N/A | 51
1996/07/22 |  N/A | 52
1996/07/15 |  N/A | 54
1996/07/08 |  N/A | 57
1996/07/01 |  N/A | 56
1996/06/24 |  N/A | 56
1996/06/17 |  N/A | 53
1996/06/10 |  N/A | 57
1996/06/03 |  N/A | 63
1996/05/27 |  N/A | 63
1996/05/20 |  N/A | 61
1996/05/13 |  N/A | 67
1996/05/06 |  N/A | 63
1996/04/29 |  N/A | 52
1996/04/22 |  N/A | 65
1996/04/15 |  N/A | 60
1996/04/08 |  N/A | 62
1996/04/01 |  N/A | 62
1996/03/25 |  N/A | 53
1996/03/18 |  N/A | 53
1996/03/11 |  N/A | 53
1996/03/04 |  N/A | 51
1996/02/26 |  N/A | 50
1996/02/19 |  N/A | 48
1996/02/12 |  N/A | 45
1996/02/05 |  N/A | 47
1996/01/29 |  N/A | 46
1996/01/22 |  N/A | 45
1996/01/15 |  N/A | 45
1996/01/08 |  N/A | 69
1996/01/01 |  N/A | 69
1995/12/25 |  N/A | 69
1995/12/18 |  N/A | 69
1995/12/11 |  N/A | 67
1995/12/04 |  N/A | 67
1995/11/27 |  N/A | 67
1995/11/20 |  N/A | 54
1995/11/13 |  N/A | 55
1995/11/06 |  N/A | 53
1995/10/30 |  N/A | 55
1995/10/23 |  N/A | 56
1995/10/16 |  N/A | 46
1995/10/09 |  N/A | 44
1995/10/02 |  N/A | 69
1995/09/25 |  N/A | 77
1995/09/18 |  N/A | 81
1995/09/11 |  N/A | 81
1995/09/04 |  N/A | 86
1995/08/28 |  N/A | 86
1995/08/21 |  N/A | 88
1995/08/14 |  N/A | 88
1995/08/07 |  N/A | 87
1995/07/31 |  N/A | 88
1995/07/24 |  N/A | 86
1995/07/17 |  N/A | 86
1995/07/10 |  N/A | 82
1995/07/03 |  N/A | 84
1995/06/26 |  N/A | 84
1995/06/19 |  N/A | 84
1995/06/12 |  N/A | 85
1995/06/05 |  N/A | 87
1995/05/29 |  N/A | 87
1995/05/22 |  N/A | 87
1995/05/15 |  N/A | 85
1995/05/08 |  N/A | 84
1995/05/01 |  N/A | 98
1995/04/24 |  N/A | 101
1995/04/17 |  N/A | 115
1995/04/10 |  N/A | 115
1995/04/03 |  N/A | 118
1995/03/27 |  N/A | 121
1995/03/20 |  N/A | 135
1995/03/13 |  N/A | 135
1995/03/06 |  N/A | 134
1995/02/27 |  N/A | 138
1995/02/20 |  N/A | 140
1995/02/13 |  N/A | 140
1995/02/06 |  N/A | 143
1995/01/30 |  N/A | 147
1995/01/23 |  N/A | 148
1995/01/16 |  N/A | 148
1995/01/09 |  N/A | 147
1995/01/02 |  N/A | 148
1994/12/26 |  N/A | 148
1994/12/19 |  N/A | 148
1994/12/12 |  N/A | 146
1994/12/05 |  N/A | 153
1994/11/28 |  N/A | 153
1994/11/21 |  N/A | 187
1994/11/14 |  N/A | 195
1994/11/07 |  N/A | 195
1994/10/31 |  N/A | 197
1994/10/24 |  N/A | 177
1994/10/17 |  N/A | 234
1994/10/10 |  N/A | 242
1994/10/03 |  N/A | 250
1994/09/26 |  N/A | 273
1994/09/19 |  N/A | 274
1994/09/12 |  N/A | 269
1994/09/05 |  N/A | 267
1994/08/29 |  N/A | 267
1994/08/22 |  N/A | 267
1994/08/15 |  N/A | 266
1994/08/08 |  N/A | 266
1994/08/01 |  N/A | 269
1994/07/25 |  N/A | 281
1994/07/18 |  N/A | 285
1994/07/11 |  N/A | 292
1994/07/04 |  N/A | 296
1994/06/27 |  N/A | 292
1994/06/20 |  N/A | 292
1994/06/13 |  N/A | 293
1994/06/06 |  N/A | 330
1994/05/30 |  N/A | 333
1994/05/23 |  N/A | 333
1994/05/16 |  N/A | 326
1994/05/09 |  N/A | 326
1994/05/02 |  N/A | 324
1994/04/25 |  N/A | 322
1994/04/18 |  N/A | 321
1994/04/11 |  N/A | 318
1994/04/04 |  N/A | 319
1994/03/28 |  N/A | 323
1994/03/21 |  N/A | 321
1994/03/14 |  N/A | 319
1994/03/07 |  N/A | 319
1994/02/28 |  N/A | 436
1994/02/21 |  N/A | 438
1994/02/14 |  N/A | 439
1994/02/07 |  N/A | 436
1994/01/31 |  N/A | 438
1994/01/24 |  N/A | 444
1994/01/17 |  N/A | 444
1994/01/10 |  N/A | 443
1994/01/03 |  N/A | 442
1993/12/27 |  N/A | 442
1993/12/20 |  N/A | 442
1993/12/13 |  N/A | 440
1993/12/06 |  N/A | 437
1993/11/29 |  N/A | 468
1993/11/22 |  N/A | 464
1993/11/15 |  N/A | 464
1993/11/08 |  N/A | 466
1993/11/01 |  N/A | 467
1993/10/25 |  N/A | 796
1993/10/18 |  N/A | 794
1993/10/11 |  N/A | 784
1993/10/04 |  N/A | 778
1993/09/27 |  N/A | 782
1993/09/20 |  N/A | 743
1993/09/13 |  N/A | 735
1993/09/06 |  N/A | 737
1993/08/30 |  N/A | 737
1993/08/23 |  N/A | 736
1993/08/16 |  N/A | 740
1993/08/09 |  N/A | 726
1993/08/02 |  N/A | 723
1993/07/26 |  N/A | 719
1993/07/19 |  N/A | 714
1993/07/12 |  N/A | 1012
1993/07/05 |  N/A | 989
1993/06/28 |  N/A | 995
1993/06/21 |  N/A | 995
1993/06/14 |  N/A | 992
1993/06/07 |  N/A | 1000
1993/05/31 |  N/A | 991
1993/05/24 |  N/A | 991
1993/05/17 |  N/A | 991
1993/05/10 |  N/A | 988
1993/05/03 |  N/A | 990
1993/04/26 |  N/A | 987
1993/04/19 |  N/A | 979
1993/04/12 |  N/A | 969
1993/04/05 |  N/A | 968
1993/03/29 |  N/A | 961
1993/03/22 |  N/A | 961
1993/03/15 |  N/A | 966
1993/03/08 |  N/A | 966
1993/03/01 |  N/A | 959
1993/02/22 |  N/A | 955
1993/02/15 |  N/A | 959
1993/02/08 |  N/A | 958
1993/02/01 |  N/A | 959
1993/01/25 |  N/A | 951
1993/01/18 |  N/A | 951
1993/01/11 |  N/A | 950
1993/01/04 |  N/A | 947
1992/12/28 |  N/A | 947
1992/12/21 |  N/A | 947
1992/12/14 |  N/A | 958
1992/12/07 |  N/A | 958
1992/11/30 |  N/A | 944
1992/11/23 |  N/A | 953
1992/11/16 |  N/A | 960
1992/11/09 |  N/A | 961
1992/11/02 |  N/A | 960
1992/10/26 |  N/A | 956
1992/10/19 |  N/A | 961
1992/10/12 |  N/A | 964
1992/10/05 |  N/A | 964
1992/09/28 |  N/A | 957
2007/02/05 |  N/A | 0
2007/01/29 |  N/A | 0
2007/01/22 |  N/A | 0
2007/01/15 |  N/A | 0
2007/01/08 |  N/A | 0
2007/01/01 |  N/A | 0
2006/12/25 |  N/A | 0
2006/12/18 |  N/A | 0
2006/12/11 |  N/A | 0
2006/12/04 |  N/A | 0
2006/11/27 |  N/A | 0
2006/11/20 |  N/A | 0
2006/11/13 |  N/A | 0
2006/11/06 |  N/A | 0
2006/10/30 |  N/A | 0
2006/10/23 |  N/A | 0
2006/10/16 |  N/A | 0
2006/10/09 |  N/A | 0
2006/10/02 |  N/A | 0
2006/09/25 |  N/A | 0
2006/09/18 |  N/A | 0
2006/09/11 |  N/A | 0
2006/09/04 |  N/A | 0
2006/08/28 |  N/A | 0
2006/08/21 |  N/A | 0
2006/08/14 |  N/A | 0
2006/08/07 |  N/A | 0
2006/07/31 |  N/A | 0
2006/07/24 |  N/A | 0
2006/07/17 |  N/A | 0
2006/07/10 |  N/A | 0
2006/07/03 |  N/A | 0
2006/06/26 |  N/A | 0
2006/06/19 |  N/A | 0
2006/06/12 |  N/A | 0
2006/06/05 |  N/A | 0
2006/05/29 |  N/A | 0
2006/05/22 |  N/A | 0
2006/05/15 |  N/A | 0
2006/05/08 |  N/A | 0
2006/05/01 |  N/A | 0
2006/04/24 |  N/A | 0
2006/04/17 |  N/A | 0
2006/04/10 |  N/A | 0
2006/04/03 |  N/A | 0
2006/03/27 |  N/A | 0
2006/03/20 |  N/A | 0
2006/03/13 |  N/A | 0
2006/03/06 |  N/A | 0
2006/02/27 |  N/A | 0
2006/02/20 |  N/A | 0
2006/02/13 |  N/A | 0
2006/02/06 |  N/A | 0
2006/01/30 |  N/A | 0
2006/01/23 |  N/A | 0
2006/01/16 |  N/A | 0
2006/01/09 |  N/A | 0
2006/01/02 |  N/A | 0
2005/12/26 |  N/A | 0
2005/12/19 |  N/A | 0
2005/12/12 |  N/A | 0
2005/12/05 |  N/A | 0
2005/11/28 |  N/A | 0
2005/11/21 |  N/A | 0
2005/11/14 |  N/A | 0
2005/11/07 |  N/A | 0
2005/10/31 |  N/A | 0
2005/10/24 |  N/A | 0
2005/10/17 |  N/A | 0
2005/10/10 |  N/A | 0
2005/10/03 |  N/A | 0
2005/09/26 |  N/A | 0
2005/09/19 |  N/A | 0
2005/09/12 |  N/A | 0
2005/09/05 |  N/A | 0
2005/08/29 |  N/A | 0
2005/08/22 |  N/A | 0
2005/08/15 |  N/A | 0
2005/08/08 |  N/A | 0
2005/08/01 |  N/A | 0
2005/07/25 |  N/A | 0
2005/07/18 |  N/A | 0
2005/07/11 |  N/A | 0
2005/07/04 |  N/A | 0
2005/06/27 |  N/A | 0
2005/06/20 |  N/A | 0
2005/06/13 |  N/A | 0
2005/06/06 |  N/A | 0
2005/05/30 |  N/A | 0
2005/05/23 |  N/A | 0
2005/05/16 |  N/A | 0
2005/05/09 |  N/A | 0
2005/05/02 |  N/A | 0
2005/04/25 |  N/A | 0
2005/04/18 |  N/A | 0
2005/04/11 |  N/A | 0
2005/04/04 |  N/A | 0
2005/03/28 |  N/A | 0
2005/03/21 |  N/A | 0
2005/03/14 |  N/A | 0
2005/03/07 |  N/A | 0
2005/02/28 |  N/A | 1461
2005/02/21 |  N/A | 1461
2005/02/14 |  N/A | 1457
2005/02/07 |  N/A | 1451
2005/01/31 |  N/A | 1440
2005/01/24 |  N/A | 0
2005/01/17 |  N/A | 1439
2005/01/10 |  N/A | 1438
2005/01/03 |  N/A | 0
2004/12/27 |  N/A | 0